import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { EdgeFunctionService } from '../../core/api/edge-function.service';
import { PeriodContextService } from '../../core/services/period-context.service';
import { ToastService } from '../../core/services/toast.service';
import { formatMoney } from '../../core/utils/money.util';
@Component({selector:'app-fund-profit',standalone:true,imports:[FormsModule],template:`
<section class="page-header"><div><p class="eyebrow">TÀI CHÍNH</p><h1>Quỹ & chia lợi nhuận</h1></div></section>@if(error()){<div class="alert">{{error()}}</div>}<div class="grid-2"><section class="card section-card"><h2>Quỹ kỳ này</h2>@for(f of fund();track f.id){<div class="stat-list"><div><span>{{f.type}}</span><strong>{{money(f.amount)}}</strong></div></div>}@empty{<p class="muted">Chưa chốt kỳ.</p>}</section><section class="card section-card"><h2>Người nhận</h2><form (ngSubmit)="save()"><div class="form-grid"><label>Tên người nhận<input name="name" [(ngModel)]="form.recipient_name" /></label><label>Tỷ lệ (%)<input name="ratio" type="number" min="0" max="100" step="0.01" [(ngModel)]="form.ratioPercent" /></label></div><button class="primary">Lưu tỷ lệ</button></form>@for(d of distributions();track d.id){<div class="stat-list"><div><span>{{d.recipient_name}} · {{(d.ratio*100).toFixed(2)}}%</span><strong>{{money(d.amount)}}</strong></div></div>}</section></div>
`})
export class FundProfitComponent implements OnInit{fund=signal<any[]>([]);distributions=signal<any[]>([]);error=signal('');form={recipient_name:'',ratioPercent:100};constructor(private readonly supabase:SupabaseService,readonly period:PeriodContextService,private readonly edge:EdgeFunctionService,private readonly toast:ToastService){}ngOnInit(){void this.load();}async load(){const p=this.period.current();if(!p)return;const [f,d]=await Promise.all([this.supabase.client.from('fund_ledger').select('*').eq('period_id',p.id),this.supabase.client.from('profit_distributions').select('*').eq('period_id',p.id)]);if(f.error||d.error)this.error.set((f.error||d.error)?.message||'Không thể tải quỹ.');else{this.fund.set(f.data||[]);this.distributions.set(d.data||[]);}}async save(){const p=this.period.current();if(!p||!this.form.recipient_name.trim()||this.form.ratioPercent<0||this.form.ratioPercent>100){this.error.set('Tên và tỷ lệ hợp lệ là bắt buộc.');return;}try{await this.edge.invoke('update-profit-distribution',{period_id:p.id,recipient_name:this.form.recipient_name,ratio:Number(this.form.ratioPercent)/100});this.toast.success('Đã lưu tỷ lệ chia.');await this.load();}catch(e){this.error.set(e instanceof Error?e.message:'Không thể lưu tỷ lệ.');}}money(v:unknown){return formatMoney(Number(v||0));}}
