import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { EdgeFunctionService } from '../../core/api/edge-function.service';
import { ToastService } from '../../core/services/toast.service';
import { formatMoney } from '../../core/utils/money.util';
@Component({selector:'app-payment-form',standalone:true,imports:[FormsModule,RouterLink],template:`
<section class="page-header"><div><p class="eyebrow">TÀI CHÍNH</p><h1>Ghi nhận thu học phí</h1></div><a class="secondary" routerLink="/finance/tuition">Quay lại học phí</a></section><form class="card form-card" (ngSubmit)="save()"><div class="form-grid"><label>Sổ học phí *<select name="ledger" [(ngModel)]="form.ledger_id"><option value="">Chọn học sinh</option>@for(l of ledgers;track l.id){<option [value]="l.id">{{l.enrollment?.student?.full_name}} · còn {{money(l.debt_amount)}}</option>}</select></label><label>Số tiền (VND) *<input type="number" min="1" step="1" name="amount" [(ngModel)]="form.amount" required /></label><label>Ngày thu *<input type="datetime-local" name="paid_at" [(ngModel)]="form.paid_at" required /></label><label>Phương thức<select name="method" [(ngModel)]="form.method"><option value="CASH">Tiền mặt</option><option value="BANK_TRANSFER">Chuyển khoản</option><option value="OTHER">Khác</option></select></label><label>Tham chiếu<input name="reference" [(ngModel)]="form.reference" placeholder="Mã giao dịch" /></label><label>Ghi chú<input name="note" [(ngModel)]="form.note" /></label></div>@if(error){<div class="alert">{{error}}</div>}<div class="form-actions"><button class="primary" [disabled]="saving">{{saving?'Đang ghi…':'Ghi nhận thanh toán'}}</button><a class="secondary" routerLink="/finance/tuition">Hủy</a></div></form>
`})
export class PaymentFormComponent implements OnInit{ledgers:any[]=[];saving=false;error='';form={ledger_id:'',amount:0,paid_at:new Date().toISOString().slice(0,16),method:'CASH',reference:'',note:''};constructor(private readonly route:ActivatedRoute,private readonly router:Router,private readonly supabase:SupabaseService,private readonly edge:EdgeFunctionService,private readonly toast:ToastService){}ngOnInit(){const queryId=this.route.snapshot.queryParamMap.get('ledgerId');if(queryId)this.form.ledger_id=queryId;void this.load();}async load(){const r=await this.supabase.client.from('tuition_ledgers').select('id,debt_amount,enrollment:enrollments(student:students(full_name))').order('debt_amount',{ascending:false});if(!r.error)this.ledgers=r.data||[];}async save(){this.error='';if(!this.form.ledger_id||!Number.isSafeInteger(Number(this.form.amount))||Number(this.form.amount)<=0){this.error='Chọn ledger và nhập số tiền nguyên dương.';return;}this.saving=true;try{await this.edge.invoke('record-payment',{ledger_id:this.form.ledger_id,amount:Number(this.form.amount),paid_at:new Date(this.form.paid_at).toISOString(),method:this.form.method,reference:this.form.reference,note:this.form.note});this.toast.success('Đã ghi nhận thanh toán.');await this.router.navigateByUrl('/finance/tuition');}catch(e){this.error=e instanceof Error?e.message:'Không thể ghi nhận thanh toán.';}finally{this.saving=false;}}money(v:unknown){return formatMoney(Number(v||0));}}
