import { Component, OnInit, signal } from '@angular/core';
import { EdgeFunctionService } from '../../core/api/edge-function.service';
import { PeriodContextService } from '../../core/services/period-context.service';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { ToastService } from '../../core/services/toast.service';
import { formatMoney } from '../../core/utils/money.util';
@Component({selector:'app-payroll',standalone:true,template:`
<section class="page-header"><div><p class="eyebrow">NHÂN SỰ</p><h1>Payroll</h1><p class="muted">Policy, cap và rounding được tính server-side.</p></div><div><button class="secondary" (click)="calculate(true)">Preview</button><button class="primary" (click)="calculate(false)">Lưu DRAFT</button></div></section>@if(error()){<div class="alert">{{error()}}</div>}<section class="card section-card"><div class="stat-list"><div><span>Tổng lương</span><strong>{{money(total())}}</strong></div><div><span>Policy</span><strong>{{policy()?.teacher_percent*100||25}}% GV · {{policy()?.assistant_percent*100||15}}% TG · cap {{policy()?.max_total_percent*100||40}}%</strong></div></div></section><div class="card table-wrap"><table><thead><tr><th>Nhân sự</th><th>Lớp</th><th>Vai trò</th><th>Doanh thu</th><th>%</th><th>Cơ bản đã làm tròn</th><th>Thực nhận</th></tr></thead><tbody>@for(i of items();track i.staff_id+i.class_id+i.role){<tr><td>{{i.staff_id}}</td><td>{{i.class_id}}</td><td>{{i.role}}</td><td>{{money(i.class_revenue)}}</td><td>{{(i.applied_percent*100).toFixed(2)}}%</td><td>{{money(i.base_amount)}}</td><td>{{money(i.final_amount)}}</td></tr>}@empty{<tr><td colspan="7" class="empty">Chưa có dữ liệu payroll.</td></tr>}</tbody></table></div>@if(runId()){<section class="card section-card"><p>Run: {{runId()}}</p><button class="primary" (click)="approve()">Duyệt payroll (Admin)</button></section>}
`})
export class PayrollComponent implements OnInit{items=signal<any[]>([]);policy=signal<any>(null);total=signal(0);runId=signal('');error=signal('');constructor(private readonly edge:EdgeFunctionService,readonly period:PeriodContextService,private readonly supabase:SupabaseService,private readonly toast:ToastService){}ngOnInit(){void this.loadRun();}async loadRun(){const p=this.period.current();if(!p)return;const r=await this.supabase.client.from('payroll_runs').select('id,status,total_amount').eq('period_id',p.id).maybeSingle();if(!r.error&&r.data){this.runId.set(r.data.id);this.total.set(Number(r.data.total_amount||0));const i=await this.supabase.client.from('payroll_items').select('*').eq('payroll_run_id',r.data.id);if(!i.error)this.items.set(i.data||[]);}}async calculate(dryRun:boolean){const p=this.period.current();if(!p)return;try{const result=await this.edge.invoke<any>('calculate-payroll',{period_id:p.id,dry_run:dryRun});this.items.set(result.items||[]);this.total.set(Number(result.total_amount||0));this.policy.set(result.policy);if(!dryRun){this.runId.set(result.payroll_run_id);this.toast.success('Đã lưu payroll DRAFT.');}}catch(e){this.error.set(e instanceof Error?e.message:'Không thể tính payroll.');}}async approve(){try{await this.edge.invoke('approve-payroll',{payroll_run_id:this.runId()});this.toast.success('Đã duyệt payroll.');}catch(e){this.error.set(e instanceof Error?e.message:'Không thể duyệt payroll.');}}money(v:unknown){return formatMoney(Number(v||0));}}
