import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { EdgeFunctionService } from '../../core/api/edge-function.service';
import { PeriodContextService } from '../../core/services/period-context.service';
import { ToastService } from '../../core/services/toast.service';
import { formatMoney } from '../../core/utils/money.util';
@Component({selector:'app-rewards',standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="page-header"><div><p class="eyebrow">TÀI CHÍNH</p><h1>Thưởng học sinh</h1></div></section><form class="card form-card" (ngSubmit)="save()"><div class="form-grid"><label>Học sinh<select name="student" [(ngModel)]="form.student_id"><option value="">Chọn học sinh</option>@for(s of students;track s.id){<option [value]="s.id">{{s.code}} · {{s.full_name}}</option>}</select></label><label>Số tiền VND<input type="number" min="0" step="1" name="amount" [(ngModel)]="form.amount" /></label><label class="full">Lý do *<input name="reason" [(ngModel)]="form.reason" /></label></div>@if(error()){<div class="alert">{{error()}}</div>}<button class="primary">Ghi thưởng</button></form><div class="card table-wrap"><table><thead><tr><th>Học sinh</th><th>Lý do</th><th>Số tiền</th><th>Ngày</th></tr></thead><tbody>@for(r of items();track r.id){<tr><td>{{r.student?.full_name}}</td><td>{{r.reason}}</td><td>{{money(r.amount)}}</td><td>{{r.created_at|slice:0:10}}</td></tr>}@empty{<tr><td colspan="4" class="empty">Chưa có thưởng.</td></tr>}</tbody></table></div>
`})
export class RewardsComponent implements OnInit{items=signal<any[]>([]);students:any[]=[];error=signal('');form={student_id:'',amount:0,reason:''};constructor(private readonly supabase:SupabaseService,readonly period:PeriodContextService,private readonly edge:EdgeFunctionService,private readonly toast:ToastService){}ngOnInit(){void this.load();}async load(){const p=this.period.current();if(!p)return;const [r,s]=await Promise.all([this.supabase.client.from('student_rewards').select('*,student:students(full_name)').eq('period_id',p.id).order('created_at',{ascending:false}),this.supabase.client.from('students').select('id,code,full_name').eq('status','ACTIVE').order('full_name')]);if(r.error||s.error)this.error.set((r.error||s.error)?.message||'Không thể tải dữ liệu.');else{this.items.set(r.data||[]);this.students=s.data||[];}}async save(){const p=this.period.current();if(!p||!this.form.student_id||!this.form.reason.trim()){this.error.set('Chọn học sinh và nhập lý do.');return;}try{await this.edge.invoke('record-student-reward',{period_id:p.id,...this.form,amount:Number(this.form.amount)});this.toast.success('Đã ghi thưởng.');this.form={student_id:'',amount:0,reason:''};await this.load();}catch(e){this.error.set(e instanceof Error?e.message:'Không thể ghi thưởng.');}}money(v:unknown){return formatMoney(Number(v||0));}}
