import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { EdgeFunctionService } from '../../core/api/edge-function.service';
import { PeriodContextService } from '../../core/services/period-context.service';
import { ToastService } from '../../core/services/toast.service';
import { formatMoney } from '../../core/utils/money.util';
@Component({selector:'app-transactions',standalone:true,imports:[FormsModule],template:`
<section class="page-header"><div><p class="eyebrow">TÀI CHÍNH</p><h1>Thu / chi khác</h1></div><button class="primary" (click)="showForm=!showForm">{{showForm?'Đóng':'+ Ghi giao dịch'}}</button></section>@if(showForm){<form class="card form-card" (ngSubmit)="save()"><div class="form-grid"><label>Ngày *<input type="date" name="date" [(ngModel)]="form.transaction_date" required /></label><label>Loại<select name="type" [(ngModel)]="form.type"><option value="INCOME">Thu</option><option value="EXPENSE">Chi</option></select></label><label>Nhóm *<input name="category" [(ngModel)]="form.category" required /></label><label>Số tiền VND *<input type="number" name="amount" min="1" step="1" [(ngModel)]="form.amount" required /></label><label class="full">Nội dung *<input name="description" [(ngModel)]="form.description" required /></label></div>@if(error()){<div class="alert">{{error()}}</div>}<button class="primary">Lưu giao dịch</button></form>}@if(!showForm&&error()){<div class="alert">{{error()}}</div>}<div class="card table-wrap"><table><thead><tr><th>Ngày</th><th>Loại</th><th>Nhóm</th><th>Nội dung</th><th>Số tiền</th></tr></thead><tbody>@for(t of items();track t.id){<tr><td>{{t.transaction_date}}</td><td>{{t.type==='INCOME'?'Thu':'Chi'}}</td><td>{{t.category}}</td><td>{{t.description}}</td><td [class.success]="t.type==='INCOME'" [class.danger]="t.type==='EXPENSE'">{{money(t.amount)}}</td></tr>}@empty{<tr><td colspan="5" class="empty">Chưa có giao dịch khác.</td></tr>}</tbody></table></div>
`})
export class TransactionsComponent implements OnInit{items=signal<any[]>([]);showForm=false;error=signal('');form={transaction_date:new Date().toISOString().slice(0,10),type:'EXPENSE',category:'',description:'',amount:0};constructor(private readonly supabase:SupabaseService,readonly period:PeriodContextService,private readonly edge:EdgeFunctionService,private readonly toast:ToastService){}ngOnInit(){void this.load();}async load(){const p=this.period.current();if(!p)return;const r=await this.supabase.client.from('financial_transactions').select('*').eq('period_id',p.id).is('voided_at',null).order('transaction_date',{ascending:false});if(r.error)this.error.set(r.error.message);else this.items.set(r.data||[]);}async save(){const p=this.period.current();if(!p||!this.form.category.trim()||!this.form.description.trim()||!Number.isSafeInteger(Number(this.form.amount))||Number(this.form.amount)<=0){this.error.set('Kỳ, metadata và số tiền là bắt buộc.');return;}try{await this.edge.invoke('record-financial-transaction',{period_id:p.id,...this.form,amount:Number(this.form.amount)});this.toast.success('Đã ghi giao dịch.');this.showForm=false;await this.load();}catch(e){this.error.set(e instanceof Error?e.message:'Không thể lưu giao dịch.');}}money(v:unknown){return formatMoney(Number(v||0));}}
