import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AuthService } from '../../core/auth/auth.service';
import { Assignment, CenterClass, ClassSession, Enrollment, MinimalService, Schedule, Staff, Student } from '../../core/services/minimal.service';
import { StatusBadgeComponent } from '../../shared/components/status-badge.component';

const weekdays = ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'Chủ nhật'];
type Detail = { item: CenterClass; schedules: Schedule[]; assignments: Assignment[]; enrollments: Enrollment[]; sessions: ClassSession[] };

@Component({
  selector: 'app-class-detail',
  standalone: true,
  imports: [FormsModule, RouterLink, StatusBadgeComponent],
  template: `
    @if (loading()) { <section class="card loading-state"><span class="loading-spinner"></span><span>Đang tải lớp…</span></section> } @else if (error()) { <div class="alert">{{ error() }}</div> } @else if (detail()) {
      <section class="page-header"><div><p class="eyebrow">LỚP HỌC</p><h1>{{ detail()!.item.name }}</h1><p class="muted">{{ detail()!.item.code }} · Khối {{ detail()!.item.grade }} · {{ detail()!.item.subject }}</p></div><a class="secondary" routerLink="/classes">Danh sách lớp</a></section>
      @if (auth.role() === 'ADMIN' && editingClass()) { <form class="card form-card section-heading-spaced" (ngSubmit)="saveClass()"><div class="panel-heading"><h2>Sửa thông tin lớp</h2><button type="button" class="secondary" (click)="editingClass.set(false)">Đóng</button></div><div class="form-grid"><label>Mã lớp<input name="code" [(ngModel)]="classForm.code" required /></label><label>Tên lớp<input name="name" [(ngModel)]="classForm.name" required /></label><label>Khối<input name="grade" type="number" min="1" max="12" [(ngModel)]="classForm.grade" required /></label><label>Môn học<input name="subject" [(ngModel)]="classForm.subject" required /></label><label class="span-2">Ghi chú<textarea name="note" rows="2" [(ngModel)]="classForm.note"></textarea></label></div><div class="form-actions"><button class="primary" type="submit" [disabled]="saving">Lưu</button></div></form> }
      <div class="detail-grid"><section class="card section-card"><div class="panel-heading"><div><p class="eyebrow">THÔNG TIN</p><h2>Thông tin lớp</h2></div>@if (auth.role() === 'ADMIN') { <button class="secondary" type="button" (click)="startClassEdit()">Sửa</button> }</div><div class="stat-list"><div><span>Mã lớp</span><strong>{{ detail()!.item.code }}</strong></div><div><span>Trạng thái</span><app-status-badge [value]="detail()!.item.status" /></div><div><span>Học sinh active</span><strong>{{ activeEnrollments().length }}</strong></div></div></section>
      <section class="card section-card"><div class="panel-heading"><div><p class="eyebrow">LỊCH TUẦN</p><h2>{{ detail()!.schedules.length }} lịch</h2></div></div>@if (auth.role() === 'ADMIN') { <form class="inline-form" (ngSubmit)="saveSchedule()"><select name="weekday" [(ngModel)]="scheduleForm.weekday">@for (day of weekdayLabels; track day; let i = $index) { <option [value]="i + 1">{{ day }}</option> }</select><input name="start_time" type="time" [(ngModel)]="scheduleForm.start_time" /><input name="end_time" type="time" [(ngModel)]="scheduleForm.end_time" /><button class="primary" type="submit">Thêm</button></form> }<div class="simple-list">@for (schedule of detail()!.schedules; track schedule.id) { <div><strong>{{ weekday(schedule.weekday) }}</strong><span>{{ schedule.start_time || 'Chưa đặt giờ' }}{{ schedule.end_time ? ' – ' + schedule.end_time : '' }}</span></div> } @empty { <p class="muted">Chưa có lịch tuần.</p> }</div></section></div>
      <section class="card section-card"><div class="panel-heading"><div><p class="eyebrow">PHÂN CÔNG</p><h2>Nhân sự phụ trách</h2></div></div>@if (auth.role() === 'ADMIN') { <form class="inline-form" (ngSubmit)="saveAssignment()"><select name="staff_id" [(ngModel)]="assignmentForm.staff_id" required><option value="">Chọn nhân sự</option>@for (staff of staffList(); track staff.id) { <option [value]="staff.id">{{ staff.code }} · {{ staff.full_name }}</option> }</select><select name="role" [(ngModel)]="assignmentForm.role"><option value="TEACHER">Giáo viên</option><option value="ASSISTANT">Trợ giảng</option></select><input name="start_date" type="date" [(ngModel)]="assignmentForm.start_date" required /><button class="primary" type="submit">Phân công</button></form> }<div class="simple-list">@for (assignment of detail()!.assignments; track assignment.id) { <div><strong>{{ assignment.staff?.full_name || assignment.staff_id }}</strong><span>{{ assignment.role === 'TEACHER' ? 'Giáo viên' : 'Trợ giảng' }} · từ {{ assignment.start_date }}</span></div> } @empty { <p class="muted">Chưa có phân công.</p> }</div></section>
      <section class="card section-card"><div class="panel-heading"><div><p class="eyebrow">ROSTER</p><h2>{{ activeEnrollments().length }} học sinh</h2></div>@if (auth.role() === 'ADMIN') { <form class="inline-form" (ngSubmit)="addEnrollment()"><select name="student_id" [(ngModel)]="newStudentId" required><option value="">Chọn học sinh</option>@for (student of availableStudents(); track student.id) { <option [value]="student.id">{{ student.code }} · {{ student.full_name }}</option> }</select><input name="enrolled_from" type="date" [(ngModel)]="enrolledFrom" required /><button class="primary" type="submit">Thêm vào lớp</button></form> }</div><div class="table-wrap"><table><thead><tr><th>Mã HS</th><th>Họ tên</th><th>Ngày vào</th><th>Trạng thái</th></tr></thead><tbody>@for (enrollment of activeEnrollments(); track enrollment.id) { <tr><td>{{ enrollment.student?.code }}</td><td>{{ enrollment.student?.full_name }}</td><td>{{ enrollment.enrolled_from }}</td><td><app-status-badge [value]="enrollment.status" /></td></tr> } @empty { <tr><td colspan="4" class="empty">Chưa có học sinh active.</td></tr> }</tbody></table></div></section>
      <section class="card section-card"><div class="panel-heading"><div><p class="eyebrow">BUỔI HỌC</p><h2>{{ detail()!.sessions.length }} buổi gần nhất</h2></div><div class="form-actions">@if (auth.role() === 'ADMIN') { <input type="date" [(ngModel)]="sessionFrom" aria-label="Từ ngày sinh buổi" /><input type="date" [(ngModel)]="sessionTo" aria-label="Đến ngày sinh buổi" /><button class="primary" type="button" [disabled]="generating" (click)="generateSessions()">{{ generating ? 'Đang sinh…' : 'Sinh buổi học' }}</button> }</div></div><div class="table-wrap"><table><thead><tr><th>Ngày</th><th>Giờ</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>@for (session of detail()!.sessions; track session.id) { <tr><td>{{ session.session_date }}</td><td>{{ session.start_time || '—' }}{{ session.end_time ? ' – ' + session.end_time : '' }}</td><td><app-status-badge [value]="session.status" /></td><td class="table-actions"><a class="button-link" [routerLink]="['/classes', id, 'sessions', session.id, 'attendance']">Điểm danh</a><a class="button-link" [routerLink]="['/classes', id, 'sessions', session.id, 'evaluation']">Nhận xét</a></td></tr> } @empty { <tr><td colspan="4" class="empty">Chưa có buổi học. Admin sinh buổi theo khoảng ngày.</td></tr> }</tbody></table></div></section>
    }
  `,
})
export class ClassDetailComponent implements OnInit {
  readonly detail = signal<Detail | null>(null); readonly staffList = signal<Staff[]>([]); readonly allStudents = signal<Student[]>([]); readonly loading = signal(true); readonly error = signal(''); readonly editingClass = signal(false);
  readonly weekdayLabels = weekdays; id = ''; saving = false; generating = false; newStudentId = ''; enrolledFrom = MinimalService.iso(new Date()); sessionFrom = MinimalService.iso(new Date()); sessionTo = MinimalService.iso(new Date(Date.now() + 30 * 86400000));
  classForm = { code: '', name: '', grade: 1, subject: '', note: '' }; scheduleForm = { weekday: 1, start_time: '', end_time: '' }; assignmentForm = { staff_id: '', role: 'TEACHER', start_date: MinimalService.iso(new Date()) };
  constructor(private readonly route: ActivatedRoute, readonly auth: AuthService, private readonly minimal: MinimalService) {}
  ngOnInit(): void { this.id = this.route.snapshot.paramMap.get('id') || ''; void this.load(); }
  async load(): Promise<void> { this.loading.set(true); this.error.set(''); try { const [detail, staff, students] = await Promise.all([this.minimal.classDetail(this.id), this.minimal.listStaff(), this.minimal.listStudents()]); this.detail.set(detail); this.staffList.set(staff); this.allStudents.set(students); const item = detail.item; this.classForm = { code: item.code, name: item.name, grade: item.grade, subject: item.subject, note: item.note || '' }; } catch (error) { this.error.set(error instanceof Error ? error.message : 'Không thể tải lớp.'); } finally { this.loading.set(false); } }
  activeEnrollments(): Enrollment[] { return this.detail()?.enrollments.filter((item) => item.status === 'ACTIVE') ?? []; }
  availableStudents(): Student[] { const enrolled = new Set(this.activeEnrollments().map((item) => item.student_id)); return this.allStudents().filter((item) => item.status === 'ACTIVE' && !enrolled.has(item.id)); }
  weekday(value: number): string { return weekdays[value - 1] || `Thứ ${value}`; }
  startClassEdit(): void { this.editingClass.set(true); }
  async saveClass(): Promise<void> { this.saving = true; try { await this.minimal.upsertClass({ class_id: this.id, ...this.classForm, grade: Number(this.classForm.grade), status: 'ACTIVE' }); this.editingClass.set(false); await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Không thể lưu lớp.'); } finally { this.saving = false; } }
  async saveSchedule(): Promise<void> { try { await this.minimal.upsertSchedule({ schedule_id: null, class_id: this.id, weekday: Number(this.scheduleForm.weekday), start_time: this.scheduleForm.start_time || null, end_time: this.scheduleForm.end_time || null, active: true }); this.scheduleForm = { weekday: 1, start_time: '', end_time: '' }; await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Không thể lưu lịch.'); } }
  async saveAssignment(): Promise<void> { try { await this.minimal.upsertAssignment({ assignment_id: null, class_id: this.id, staff_id: this.assignmentForm.staff_id, role: this.assignmentForm.role, start_date: this.assignmentForm.start_date, end_date: null, active: true }); this.assignmentForm = { staff_id: '', role: 'TEACHER', start_date: MinimalService.iso(new Date()) }; await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Không thể phân công nhân sự.'); } }
  async addEnrollment(): Promise<void> { try { await this.minimal.upsertEnrollment({ enrollment_id: null, student_id: this.newStudentId, class_id: this.id, enrolled_from: this.enrolledFrom, enrolled_to: null, status: 'ACTIVE' }); this.newStudentId = ''; await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Không thể thêm học sinh.'); } }
  async generateSessions(): Promise<void> { this.generating = true; try { await this.minimal.generateSessions(this.sessionFrom, this.sessionTo); await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Không thể sinh buổi học.'); } finally { this.generating = false; } }
}
