import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { ToastService } from '../../core/services/toast.service';

type Day = { value: number; label: string; selected: boolean; start: string; end: string };
@Component({ selector: 'app-class-form', standalone: true, imports: [FormsModule, RouterLink], template: `
  <section class="page-header"><div><p class="eyebrow">ĐÀO TẠO</p><h1>Tạo lớp học</h1></div><a class="secondary" routerLink="/classes">Quay lại</a></section>
  <form class="card form-card" (ngSubmit)="save()"><div class="form-grid"><label>Mã lớp *<input name="code" [(ngModel)]="form.code" required placeholder="L06" /></label><label>Tên lớp *<input name="name" [(ngModel)]="form.name" required /></label><label>Khối *<input name="grade" type="number" min="1" max="12" [(ngModel)]="form.grade" required /></label><label>Môn *<input name="subject" [(ngModel)]="form.subject" required /></label><label>Học phí/buổi (VND) *<input name="fee" type="number" min="0" step="1" [(ngModel)]="form.fee" required /></label><label>Cách thu<select name="method" [(ngModel)]="form.method"><option value="PER_SESSION">Theo buổi</option><option value="PREPAID">Thu trước</option></select></label><label class="full">Ghi chú<textarea name="note" rows="3" [(ngModel)]="form.note"></textarea></label></div><h3>Lịch học tuần</h3><div class="check-grid">@for (day of days; track day.value) { <label><input type="checkbox" [(ngModel)]="day.selected" [name]="'day' + day.value" />{{ day.label }}<input type="time" [(ngModel)]="day.start" [name]="'start' + day.value" /><input type="time" [(ngModel)]="day.end" [name]="'end' + day.value" /></label> }</div>@if (error) { <div class="alert">{{ error }}</div> }<div class="form-actions"><button class="primary" [disabled]="saving">{{ saving ? 'Đang lưu…' : 'Lưu lớp' }}</button><a class="secondary" routerLink="/classes">Hủy</a></div></form>
` })
export class ClassFormComponent {
  form = { code: '', name: '', grade: 6, subject: 'Toán', fee: 50000, method: 'PER_SESSION', note: '' }; saving = false; error = '';
  days: Day[] = [{value:1,label:'Thứ 2',selected:false,start:'',end:''},{value:2,label:'Thứ 3',selected:false,start:'',end:''},{value:3,label:'Thứ 4',selected:false,start:'',end:''},{value:4,label:'Thứ 5',selected:false,start:'',end:''},{value:5,label:'Thứ 6',selected:false,start:'',end:''},{value:6,label:'Thứ 7',selected:false,start:'',end:''},{value:7,label:'Chủ nhật',selected:false,start:'',end:''}];
  constructor(private readonly supabase: SupabaseService, private readonly router: Router, private readonly toast: ToastService) {}
  async save(): Promise<void> { this.error = ''; if (!this.form.code.trim() || !this.form.name.trim() || !Number.isSafeInteger(Number(this.form.fee)) || this.form.fee < 0 || this.form.grade < 1 || this.form.grade > 12) { this.error = 'Vui lòng kiểm tra các trường bắt buộc.'; return; } this.saving = true; try { const schedules = this.days.filter((day) => day.selected).map((day) => ({ weekday: day.value, start_time: day.start || null, end_time: day.end || null })); const result = await this.supabase.client.rpc('rpc_create_class_with_schedules', { p_code: this.form.code.trim(), p_name: this.form.name.trim(), p_grade: this.form.grade, p_subject: this.form.subject.trim(), p_standard_unit_fee: this.form.fee, p_collection_method: this.form.method, p_note: this.form.note.trim() || null, p_schedules: schedules, p_effective_from: new Date().toISOString().slice(0,10) }); if (result.error) throw result.error; const classId = (result.data as any)?.class_id; if (!classId) throw new Error('Không nhận được mã lớp mới.'); this.toast.success('Đã tạo lớp học.'); await this.router.navigate(['/classes', classId]); } catch (error) { this.error = error instanceof Error ? error.message : 'Không thể tạo lớp.'; } finally { this.saving = false; } }
}
