import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { EdgeFunctionService } from '../../core/api/edge-function.service';
import { PeriodContextService } from '../../core/services/period-context.service';
import { ToastService } from '../../core/services/toast.service';
import { AuthService } from '../../core/auth/auth.service';
import { StatusBadgeComponent } from '../../shared/components/status-badge.component';
@Component({selector:'app-class-schedule',standalone:true,imports:[FormsModule,RouterLink,StatusBadgeComponent],template:`
<section class="page-header"><div><p class="eyebrow">LỚP HỌC</p><h1>Lịch học & buổi học</h1></div><a class="secondary" [routerLink]="['/classes',id]">Chi tiết lớp</a></section>@if(error()){<div class="alert">{{error()}}</div>}<section class="card section-card"><h2>Lịch tuần</h2><div class="toolbar"><label>Thứ<select [(ngModel)]="schedule.weekday">@for(day of days;track day.value){<option [value]="day.value">{{day.label}}</option>}</select></label><label>Bắt đầu<input type="time" [(ngModel)]="schedule.start_time" /></label><label>Kết thúc<input type="time" [(ngModel)]="schedule.end_time" /></label>@if(auth.role()==='ADMIN'){<button class="primary" (click)="addSchedule()">Thêm lịch</button>}</div><div class="check-grid">@for(item of schedules();track item.id){<span class="badge active">{{dayLabel(item.weekday)}} {{item.start_time||''}}–{{item.end_time||''}}</span>}</div></section><section class="card section-card"><div class="page-header"><h2>Buổi trong kỳ</h2>@if(auth.role()==='ADMIN'){<button class="primary" [disabled]="!period.current()||generating" (click)="generate()">{{generating?'Đang sinh…':'Sinh buổi theo lịch'}}</button>}</div><div class="table-wrap"><table><thead><tr><th>Ngày</th><th>Giờ</th><th>Trạng thái</th></tr></thead><tbody>@for(item of sessions();track item.id){<tr><td>{{item.session_date}}</td><td>{{item.start_time||'—'}}</td><td><app-status-badge [value]="item.status" /></td></tr>}@empty{<tr><td colspan="3" class="empty">Chưa có buổi. Chọn kỳ rồi sinh buổi.</td></tr>}</tbody></table></div></section>
`})
export class ClassScheduleComponent implements OnInit{id='';schedules=signal<any[]>([]);sessions=signal<any[]>([]);error=signal('');generating=false;schedule={weekday:2,start_time:'',end_time:''};days=[{value:1,label:'Thứ 2'},{value:2,label:'Thứ 3'},{value:3,label:'Thứ 4'},{value:4,label:'Thứ 5'},{value:5,label:'Thứ 6'},{value:6,label:'Thứ 7'},{value:7,label:'Chủ nhật'}];constructor(private readonly route:ActivatedRoute,private readonly supabase:SupabaseService,readonly period:PeriodContextService,private readonly edge:EdgeFunctionService,private readonly toast:ToastService,readonly auth:AuthService){}ngOnInit(){this.id=this.route.snapshot.paramMap.get('id')||'';void this.load();}async load(){await this.period.ready;const s=await this.supabase.client.from('class_schedules').select('*').eq('class_id',this.id).eq('active',true).order('weekday');if(!s.error)this.schedules.set(s.data||[]);const p=this.period.current();if(p){const x=await this.supabase.client.from('class_sessions').select('*').eq('class_id',this.id).eq('period_id',p.id).order('session_date');if(!x.error)this.sessions.set(x.data||[]);}}async addSchedule(){const result=await this.supabase.client.from('class_schedules').insert({class_id:this.id,weekday:Number(this.schedule.weekday),start_time:this.schedule.start_time||null,end_time:this.schedule.end_time||null,effective_from:new Date().toISOString().slice(0,10)});if(result.error)this.error.set(result.error.message);else{this.toast.success('Đã thêm lịch tuần.');await this.load();}}async generate(){await this.period.ready;const p=this.period.current();if(!p)return;this.generating=true;try{await this.edge.invoke('generate-month-sessions',{class_id:this.id,period_id:p.id});this.toast.success('Đã sinh buổi học.');await this.load();}catch(e){this.error.set(e instanceof Error?e.message:'Không thể sinh buổi.');}finally{this.generating=false;}}dayLabel(value:number){return this.days.find(d=>d.value===Number(value))?.label||String(value);}}
