import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { WorkflowService, MonthSetupPreview } from '../../core/services/workflow.service';
import { PeriodContextService } from '../../core/services/period-context.service';
import { ToastService } from '../../core/services/toast.service';
import { PeriodsComponent } from '../periods/periods.component';

type EnrollmentAction = 'KEEP' | 'ADD' | 'MOVE' | 'LEAVE' | 'REENTRY';
type SetupClass = { code: string; name: string; grade: number; subject: string; unit_fee: number; collection_method: 'PER_SESSION' | 'PREPAID'; note?: string };
type SetupDraft = {
  year: number; month: number; start_date: string; end_date: string;
  class_configs: any[]; enrollment_actions: any[]; schedules: any[]; assignments: any[];
  settings: Record<string, unknown>; carry_over: boolean; new_classes: SetupClass[];
};

const steps = ['Tháng', 'Lớp', 'Học sinh', 'Lịch', 'Phân công', 'Lương', 'Kế toán', 'Carry-over', 'Xác nhận'];

@Component({
  selector: 'app-month-setup',
  standalone: true,
  imports: [FormsModule, RouterLink, PeriodsComponent],
  template: `
    <section class="page-header app-page-header"><div><p class="eyebrow">VẬN HÀNH THÁNG</p><h1>Tạo tháng mới</h1><p class="page-description muted">Wizard giữ draft trong trình duyệt và chỉ tạo kỳ, roster, lịch, phân công bằng một giao dịch atomic ở bước cuối.</p></div><a class="secondary" [routerLink]="['/periods']" [queryParams]="{ tab: 'manage' }">Danh sách & chốt tháng</a></section>
    <nav class="hub-tabs"><a [class.active]="tab() === 'create'" [routerLink]="['/periods']" [queryParams]="{ tab: 'create' }">Tạo tháng</a><a [class.active]="tab() === 'manage'" [routerLink]="['/periods']" [queryParams]="{ tab: 'manage' }">Danh sách & chốt</a></nav>
    @if (tab() === 'manage') { <app-periods /> } @else {
      <section class="workflow-stepper workflow-stepper-wide">@for(label of stepLabels; track label; let i = $index){<button type="button" class="workflow-step" [class.done]="i <= step()" [class.current]="i === step()" (click)="jump(i)"><span>{{ i + 1 }}</span><strong>{{ label }}</strong></button>@if(i < stepLabels.length - 1){<div class="workflow-line"></div>}}</section>
      @if (error()) { <div class="alert">{{ error() }}</div> }
      @if (loading()) { <section class="card loading-state"><span class="loading-spinner"></span><span>Đang tải snapshot để copy…</span></section> } @else {
        <section class="card section-card wizard-card">
          @switch(step()) {
            @case(0) { <div class="wizard-heading"><p class="eyebrow">BƯỚC 1 / 9</p><h2>Tháng và khoảng ngày</h2><p class="muted">Kỳ nguồn phải đóng trước khi thực hiện carry-over và tạo tháng mới.</p></div><div class="form-grid"><label>Năm *<input type="number" min="2020" max="2100" [(ngModel)]="draft.year" (ngModelChange)="saveDraft()" /></label><label>Tháng *<input type="number" min="1" max="12" [(ngModel)]="draft.month" (ngModelChange)="saveDraft()" /></label><label>Bắt đầu *<input type="date" [(ngModel)]="draft.start_date" (ngModelChange)="saveDraft()" /></label><label>Kết thúc *<input type="date" [(ngModel)]="draft.end_date" (ngModelChange)="saveDraft()" /></label></div> }
            @case(1) { <div class="wizard-heading"><p class="eyebrow">BƯỚC 2 / 9</p><h2>Lớp học của tháng</h2><p class="muted">Chọn snapshot học phí/cách thu theo tháng; lớp tắt sẽ không sinh session và ledger.</p></div><div class="setup-list">@for(config of draft.class_configs; track config.class_id){<label class="setup-row"><input type="checkbox" [checked]="config.active" (change)="config.active = $any($event.target).checked; saveDraft()" /><span><strong>{{ className(config.class_id) }}</strong><small>{{ classCode(config.class_id) }}</small></span><input class="compact-input" type="number" min="0" [value]="config.unit_fee" (input)="config.unit_fee = +$any($event.target).value; saveDraft()" /><select class="compact-select" [value]="config.collection_method" (change)="config.collection_method = $any($event.target).value; saveDraft()"><option value="PER_SESSION">Theo buổi</option><option value="PREPAID">Thu trước</option></select></label>}@empty{<p class="muted">Chưa có lớp từ snapshot nguồn.</p>}</div><div class="new-class-form"><h3>Thêm lớp mới</h3><div class="form-grid"><label>Mã lớp<input [(ngModel)]="newClass.code" /></label><label>Tên lớp<input [(ngModel)]="newClass.name" /></label><label>Khối<input type="number" min="1" max="12" [(ngModel)]="newClass.grade" /></label><label>Môn<input [(ngModel)]="newClass.subject" /></label><label>Đơn giá<input type="number" min="0" [(ngModel)]="newClass.unit_fee" /></label><label>Cách thu<select [(ngModel)]="newClass.collection_method"><option value="PER_SESSION">Theo buổi</option><option value="PREPAID">Thu trước</option></select></label></div><button class="secondary" type="button" (click)="addClass()">+ Thêm lớp vào draft</button>@for(item of draft.new_classes; track item.code){<span class="badge tone-positive">{{ item.code }} · {{ item.name }}</span>}</div> }
            @case(2) { <div class="wizard-heading"><p class="eyebrow">BƯỚC 3 / 9</p><h2>Roster học sinh</h2><p class="muted">Mặc định giữ enrollment đang active. LEFT là terminal; re-entry luôn tạo enrollment mới.</p></div><div class="table-wrap"><table><thead><tr><th>Học sinh</th><th>Lớp hiện tại</th><th>Thao tác tháng mới</th><th>Đơn giá override</th></tr></thead><tbody>@for(student of preview?.students ?? []; track student.id){@for(enrollment of activeEnrollments(student); track enrollment.id){<tr><td>{{ student.code }} · {{ student.full_name }}</td><td>{{ classCode(enrollment.class_id) }}</td><td><select [value]="actionFor(enrollment.id)" (change)="setAction(enrollment, $any($event.target).value)"><option value="KEEP">Giữ</option><option value="MOVE">Chuyển lớp</option><option value="LEAVE">Nghỉ</option><option value="REENTRY">Re-entry</option></select></td><td><input class="compact-input" type="number" min="0" [value]="enrollment.unit_price_override ?? ''" (input)="setPrice(enrollment, $any($event.target).value)" /></td></tr>}}@empty{<tr><td colspan="4" class="empty">Không có enrollment active trong snapshot nguồn.</td></tr>}</tbody></table></div> }
            @case(3) { <div class="wizard-heading"><p class="eyebrow">BƯỚC 4 / 9</p><h2>Copy và chỉnh lịch</h2><p class="muted">Lịch được gắn effective date của tháng mới và session sẽ sinh sau khi tạo kỳ.</p></div><div class="setup-list">@for(schedule of draft.schedules; track schedule.id){<label class="setup-row"><input type="checkbox" [checked]="schedule.active" (change)="schedule.active = $any($event.target).checked; saveDraft()" /><span><strong>{{ classCode(schedule.class_id) }}</strong><small>Thứ {{ schedule.weekday }} · {{ schedule.start_time || 'cả ngày' }} – {{ schedule.end_time || '—' }}</small></span><span class="muted">{{ schedule.effective_from }} → {{ schedule.effective_to || draft.end_date }}</span></label>}@empty{<p class="muted">Chưa có lịch nguồn. Có thể thêm lịch sau trong chi tiết lớp.</p>}</div> }
            @case(4) { <div class="wizard-heading"><p class="eyebrow">BƯỚC 5 / 9</p><h2>Giáo viên và trợ giảng</h2><p class="muted">Chỉ nhân sự active và role khớp staff type mới được tạo assignment.</p></div><div class="setup-list">@for(item of draft.assignments; track item.id){<div class="setup-row"><span><strong>{{ staffName(item.staff_id) }}</strong><small>{{ classCode(item.class_id) }} · {{ item.role === 'ASSISTANT' ? 'Trợ giảng' : 'Giáo viên chính' }}</small></span><input class="compact-input" type="number" min="0" [value]="item.planned_sessions ?? ''" (input)="item.planned_sessions = $any($event.target).value ? +$any($event.target).value : null; saveDraft()" /></div>}@empty{<p class="muted">Chưa có phân công nguồn.</p>}</div> }
            @case(5) { <div class="wizard-heading"><p class="eyebrow">BƯỚC 6 / 9</p><h2>Policy lương</h2><p class="muted">Tháng mới dùng basis APPROVED_WORK_ATTENDANCE. Payroll không tính dựa trên kế hoạch chưa được duyệt.</p></div><div class="policy-callout"><strong>APPROVED_WORK_ATTENDANCE</strong><span>GV/TG check-in/out theo buổi → SUBMITTED → Admin duyệt → payroll.</span></div> }
            @case(6) { <div class="wizard-heading"><p class="eyebrow">BƯỚC 7 / 9</p><h2>Cấu hình kế toán</h2><p class="muted">Snapshot quỹ và policy được lưu vào period_settings, không phụ thuộc thay đổi cấu hình master về sau.</p></div><div class="form-grid"><label>Tỷ lệ quỹ (%)<input type="number" min="0" max="100" step="0.01" [value]="fundPercent()" (input)="setFundPercent($any($event.target).value)" /></label><label>Cơ sở tính công<input value="Theo công đã duyệt" disabled /></label></div> }
            @case(7) { <div class="wizard-heading"><p class="eyebrow">BƯỚC 8 / 9</p><h2>Carry-over</h2><p class="muted">Khoản nợ dương của kỳ nguồn sẽ tạo CARRY_IN/CARRY_OUT có liên kết và idempotent.</p></div><label class="toggle-row"><input type="checkbox" [(ngModel)]="draft.carry_over" (ngModelChange)="saveDraft()" /><span><strong>Giữ carry-over công nợ</strong><small>Không xóa payment, ledger hoặc lịch sử enrollment cũ.</small></span></label> }
            @case(8) { <div class="wizard-heading"><p class="eyebrow">BƯỚC 9 / 9</p><h2>Preview và tạo tháng</h2><p class="muted">Kiểm tra payload trước khi gọi RPC atomic. Nếu có lỗi, toàn bộ transaction rollback.</p></div><div class="result-summary"><div><span>Kỳ mới</span><strong>{{ draft.month }}/{{ draft.year }}</strong></div><div><span>Lớp active</span><strong>{{ activeClassCount() }}</strong></div><div><span>Roster action</span><strong>{{ draft.enrollment_actions.length }}</strong></div><div><span>Lịch</span><strong>{{ activeScheduleCount() }}</strong></div><div><span>Phân công</span><strong>{{ draft.assignments.length }}</strong></div></div><pre class="payload-preview">{{ payloadSummary() }}</pre> }
          }
          <div class="form-actions wizard-actions"><button class="secondary" type="button" [disabled]="step() === 0" (click)="previous()">← Quay lại</button>@if(step() < stepLabels.length - 1){<button class="primary" type="button" (click)="next()">Tiếp tục →</button>}@else{<button class="primary" type="button" [disabled]="creating()" (click)="create()">{{ creating() ? 'Đang tạo atomic…' : 'Tạo tháng' }}</button>}</div>
        </section>
      }
    }
  `,
})
export class MonthSetupComponent implements OnInit {
  readonly stepLabels = steps;
  readonly tab = signal<'create' | 'manage'>('create');
  readonly step = signal(0);
  readonly loading = signal(true);
  readonly creating = signal(false);
  readonly error = signal('');
  preview: MonthSetupPreview | null = null;
  sourcePeriodId: string | null = null;
  draft: SetupDraft = this.blankDraft();
  newClass: SetupClass = { code: '', name: '', grade: 1, subject: '', unit_fee: 0, collection_method: 'PER_SESSION' };

  constructor(private readonly route: ActivatedRoute, private readonly workflow: WorkflowService, readonly period: PeriodContextService, private readonly toast: ToastService) {}
  ngOnInit(): void { this.route.queryParamMap.subscribe((params) => { this.tab.set(params.get('tab') === 'manage' ? 'manage' : 'create'); if (this.tab() === 'create' && !this.preview) void this.load(); }); }
  blankDraft(): SetupDraft { const next = new Date(); next.setMonth(next.getMonth() + 1, 1); const end = new Date(next.getFullYear(), next.getMonth() + 1, 0); return { year: next.getFullYear(), month: next.getMonth() + 1, start_date: this.iso(next), end_date: this.iso(end), class_configs: [], enrollment_actions: [], schedules: [], assignments: [], settings: { fund: { fund_percent: 0.1 } }, carry_over: true, new_classes: [] }; }
  async load(): Promise<void> { this.loading.set(true); this.error.set(''); try { await this.period.ready; this.sourcePeriodId = this.period.current()?.id ?? null; const stored = sessionStorage.getItem('hc-month-setup-draft'); this.preview = await this.workflow.monthSetupPreview(this.sourcePeriodId ?? undefined); this.draft = stored ? this.restoreDraft(stored, this.preview) : this.fromPreview(this.preview); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Không thể tải snapshot tháng.'); } finally { this.loading.set(false); } }
  fromPreview(value: MonthSetupPreview): SetupDraft { const fundSetting = value.settings.find((item: any) => item.key === 'fund')?.value_json?.fund_percent; const payrollPolicy = value.policy ? { name: value.policy.name, teacher_percent: value.policy.teacher_percent, assistant_percent: value.policy.assistant_percent, max_total_percent: value.policy.max_total_percent, rounding_step: value.policy.rounding_step } : {}; return { ...this.blankDraft(), class_configs: value.class_configs.map((item) => ({ ...item, active: item.active !== false })), enrollment_actions: value.students.flatMap((student: any) => this.activeEnrollments(student).map((enrollment: any) => ({ action: 'KEEP' as EnrollmentAction, student_id: student.id, class_id: enrollment.class_id, source_enrollment_id: enrollment.id, enrolled_from: enrollment.enrolled_from, unit_price_override: enrollment.unit_price_override, tuition_exempt: enrollment.tuition_exempt, note: enrollment.note }))), schedules: value.schedules.map((item: any) => ({ ...item, active: item.active !== false })), assignments: value.assignments.map((item: any) => ({ ...item })), settings: { fund: { fund_percent: Number(fundSetting ?? 0.1) }, payroll_policy: payrollPolicy }, carry_over: true, new_classes: [] }; }
  restoreDraft(raw: string, value: MonthSetupPreview): SetupDraft { try { const parsed = JSON.parse(raw) as SetupDraft; return { ...this.fromPreview(value), ...parsed, class_configs: parsed.class_configs ?? this.fromPreview(value).class_configs, enrollment_actions: parsed.enrollment_actions ?? this.fromPreview(value).enrollment_actions, schedules: parsed.schedules ?? this.fromPreview(value).schedules, assignments: parsed.assignments ?? this.fromPreview(value).assignments, settings: parsed.settings ?? { fund: { fund_percent: 0.1 } }, new_classes: parsed.new_classes ?? [] }; } catch { return this.fromPreview(value); } }
  saveDraft(): void { try { sessionStorage.setItem('hc-month-setup-draft', JSON.stringify(this.draft)); } catch { /* storage is optional; draft remains in memory */ } }
  className(id: string): string { return this.preview?.classes.find((item: any) => item.id === id)?.name ?? 'Lớp mới'; }
  classCode(id: string): string { return this.preview?.classes.find((item: any) => item.id === id)?.code ?? id.slice(0, 8); }
  staffName(id: string): string { const row = (this.preview?.assignments ?? []).find((item: any) => item.staff_id === id); return row?.staff?.full_name ?? id.slice(0, 8); }
  activeEnrollments(student: any): any[] { return (student.enrollments ?? []).filter((item: any) => item.status === 'ACTIVE'); }
  actionFor(enrollmentId: string): EnrollmentAction { return this.draft.enrollment_actions.find((item) => item.source_enrollment_id === enrollmentId)?.action ?? 'KEEP'; }
  setAction(enrollment: any, action: EnrollmentAction): void { const row = this.draft.enrollment_actions.find((item) => item.source_enrollment_id === enrollment.id); if (row) row.action = action; else this.draft.enrollment_actions.push({ action, student_id: '', class_id: enrollment.class_id, source_enrollment_id: enrollment.id }); this.saveDraft(); }
  setPrice(enrollment: any, value: string): void { const row = this.draft.enrollment_actions.find((item) => item.source_enrollment_id === enrollment.id); if (row) row.unit_price_override = value ? Number(value) : null; this.saveDraft(); }
  addClass(): void { if (!this.newClass.code.trim() || !this.newClass.name.trim() || !this.newClass.subject.trim() || this.newClass.grade < 1 || this.newClass.grade > 12 || this.newClass.unit_fee < 0) { this.error.set('Mã, tên, khối, môn và đơn giá lớp mới là bắt buộc.'); return; } this.draft.new_classes.push({ ...this.newClass, code: this.newClass.code.trim(), name: this.newClass.name.trim(), subject: this.newClass.subject.trim() }); this.newClass = { code: '', name: '', grade: 1, subject: '', unit_fee: 0, collection_method: 'PER_SESSION' }; this.error.set(''); this.saveDraft(); }
  fundPercent(): number { return Number((this.draft.settings['fund'] as any)?.fund_percent ?? 0.1) * 100; }
  setFundPercent(value: string): void { this.draft.settings = { ...this.draft.settings, fund: { fund_percent: Math.max(0, Math.min(100, Number(value || 0) / 100)) } }; this.saveDraft(); }
  activeClassCount(): number { return this.draft.class_configs.filter((item) => item.active).length + this.draft.new_classes.length; }
  activeScheduleCount(): number { return this.draft.schedules.filter((item) => item.active).length; }
  payloadSummary(): string { return JSON.stringify({ source_period_id: this.sourcePeriodId, period: { year: this.draft.year, month: this.draft.month, start_date: this.draft.start_date, end_date: this.draft.end_date }, class_configs: this.draft.class_configs.filter((item) => item.active), enrollment_actions: this.draft.enrollment_actions, schedules: this.draft.schedules.filter((item) => item.active), assignments: this.draft.assignments, settings: this.draft.settings, carry_over: this.draft.carry_over, new_classes: this.draft.new_classes }, null, 2); }
  validStep(): boolean { if (this.step() === 0) return Number.isInteger(this.draft.year) && this.draft.month >= 1 && this.draft.month <= 12 && !!this.draft.start_date && !!this.draft.end_date && this.draft.end_date >= this.draft.start_date; if (this.step() === 1) return this.activeClassCount() > 0 && this.draft.class_configs.filter((item) => item.active).every((item) => Number.isSafeInteger(Number(item.unit_fee)) && Number(item.unit_fee) >= 0); if (this.step() === 4) return this.draft.assignments.every((item) => Number(item.planned_sessions ?? 0) >= 0); return true; }
  next(): void { if (!this.validStep()) { this.error.set('Vui lòng hoàn thiện dữ liệu hợp lệ trước khi tiếp tục.'); return; } this.error.set(''); this.saveDraft(); this.step.update((value) => Math.min(this.stepLabels.length - 1, value + 1)); }
  previous(): void { this.error.set(''); this.step.update((value) => Math.max(0, value - 1)); }
  jump(index: number): void { if (index <= this.step()) this.step.set(index); }
  async create(): Promise<void> { if (!this.validStep()) { this.error.set('Payload tháng chưa hợp lệ.'); return; } this.creating.set(true); this.error.set(''); try { const result = await this.workflow.createMonthSetup({ source_period_id: this.sourcePeriodId, period: { year: this.draft.year, month: this.draft.month, start_date: this.draft.start_date, end_date: this.draft.end_date }, class_configs: this.draft.class_configs, enrollment_actions: this.draft.enrollment_actions, schedules: this.draft.schedules.filter((item) => item.active), assignments: this.draft.assignments, settings: this.draft.settings, carry_over: this.draft.carry_over, new_classes: this.draft.new_classes }); sessionStorage.removeItem('hc-month-setup-draft'); await this.period.load(); this.toast.success(`Đã tạo tháng ${this.draft.month}/${this.draft.year} atomic.`); this.step.set(0); this.draft = this.blankDraft(); void result; } catch (error) { this.error.set(error instanceof Error ? error.message : 'Không thể tạo tháng; transaction đã rollback nếu RPC thất bại.'); } finally { this.creating.set(false); } }
  iso(value: Date): string { return value.toISOString().slice(0, 10); }
}
