import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { ToastService } from '../../core/services/toast.service';
@Component({selector:'app-student-form',standalone:true,imports:[FormsModule,RouterLink],template:`
<section class="page-header"><div><p class="eyebrow">ĐÀO TẠO</p><h1>Thêm học sinh</h1></div><a class="secondary" routerLink="/students">Quay lại</a></section><form class="card form-card" (ngSubmit)="save()"><div class="form-grid"><label>Mã HS *<input name="code" [(ngModel)]="form.code" required placeholder="HS06-001" /></label><label>Họ tên *<input name="full_name" [(ngModel)]="form.full_name" required /></label><label>SĐT học sinh<input name="phone" [(ngModel)]="form.phone" /></label><label>Tên phụ huynh<input name="parent_name" [(ngModel)]="form.parent_name" /></label><label>SĐT phụ huynh<input name="parent_phone" [(ngModel)]="form.parent_phone" /></label><label>Lớp ban đầu<select name="class_id" [(ngModel)]="form.class_id"><option value="">Chưa xếp lớp</option>@for(c of classes;track c.id){<option [value]="c.id">{{c.code}} · {{c.name}}</option>}</select></label><label>Ngày vào lớp<input type="date" name="enrolled_from" [(ngModel)]="form.enrolled_from" /></label><label>Đơn giá riêng (VND)<input type="number" min="0" step="1" name="unit_price_override" [(ngModel)]="form.unit_price_override" /></label><label class="full">Ghi chú<textarea name="note" rows="3" [(ngModel)]="form.note"></textarea></label></div>@if(error){<div class="alert">{{error}}</div>}<div class="form-actions"><button class="primary" [disabled]="saving">{{saving?'Đang lưu…':'Lưu học sinh'}}</button><a class="secondary" routerLink="/students">Hủy</a></div></form>
`})
export class StudentFormComponent implements OnInit{classes:any[]=[];form={code:'',full_name:'',phone:'',parent_name:'',parent_phone:'',class_id:'',enrolled_from:new Date().toISOString().slice(0,10),unit_price_override:null as number|null,note:''};saving=false;error='';constructor(private readonly supabase:SupabaseService,private readonly router:Router,private readonly toast:ToastService){}ngOnInit(){void this.loadClasses();}async loadClasses(){const r=await this.supabase.client.from('classes').select('id,code,name').eq('status','ACTIVE').order('grade');if(!r.error)this.classes=r.data||[];}async save(){if(!this.form.code.trim()||!this.form.full_name.trim()||this.form.unit_price_override !== null&&(!Number.isSafeInteger(Number(this.form.unit_price_override))||Number(this.form.unit_price_override)<0)){this.error='Mã, họ tên và đơn giá phải hợp lệ.';return;}this.saving=true;this.error='';try{const result=await this.supabase.client.rpc('rpc_create_student_enrollment',{p_code:this.form.code.trim(),p_full_name:this.form.full_name.trim(),p_phone:this.form.phone.trim()||null,p_parent_name:this.form.parent_name.trim()||null,p_parent_phone:this.form.parent_phone.trim()||null,p_class_id:this.form.class_id||null,p_enrolled_from:this.form.enrolled_from,p_unit_price_override:this.form.unit_price_override,p_note:this.form.note.trim()||null});if(result.error)throw result.error;const studentId=(result.data as any)?.student_id;if(!studentId)throw new Error('Không nhận được mã học sinh mới.');this.toast.success('Đã thêm học sinh.');await this.router.navigate(['/students',studentId]);}catch(e){this.error=e instanceof Error?e.message:'Không thể thêm học sinh.';}finally{this.saving=false;}}
}
