import { withSupabase } from 'npm:@supabase/server@^1';
import { requireProfile } from '../_shared/auth.ts';
import { errorResponse, finish, preflight } from '../_shared/rpc.ts';
import { jsonBody, requiredString, requiredUuid } from '../_shared/validation.ts';
import { ok } from '../_shared/response.ts';

type Mode = 'VALIDATE' | 'IMPORT' | 'RECONCILE';
type Payload = { import_job_id?: string; file_name?: string; file_base64?: string; storage_path?: string; mode?: Mode };
type Issue = { severity: 'ERROR' | 'WARNING'; sheet_name: string; row_number?: number; code: string; message: string; raw_data?: unknown };
type PeriodPayload = { year: number; month: number; start_date: string; end_date: string };
type StudentPayload = { code: string; full_name: string; phone: string | null; parent_name: string | null; parent_phone: string | null; note: string | null; class_code: string | null; enrolled_from: string; unit_price_override: number | null };
type NormalizedPayload = {
  periods: PeriodPayload[];
  settings: Array<{ key: string; value_json: unknown }>;
  classes: Array<{ code: string; name: string; grade: number; subject: string; standard_unit_fee: number; collection_method: 'PER_SESSION' | 'PREPAID'; status: 'ACTIVE' | 'INACTIVE'; note: string | null; schedules: Array<{ weekday: number; start_time: string | null; end_time: string | null }> }>;
  staff: Array<{ code: string; full_name: string; staff_type: 'TEACHER' | 'ASSISTANT'; phone: string | null; primary_subject: string | null; status: 'ACTIVE' | 'INACTIVE'; note: string | null }>;
  assignments: Array<{ class_code: string; staff_code: string; role: 'MAIN_TEACHER' | 'ASSISTANT'; planned_sessions: number | null; start_date: string; end_date: string | null }>;
  students: StudentPayload[];
  enrollments: Array<{ student_code: string; class_code: string; enrolled_from: string; enrolled_to: string | null; unit_price_override: number | null; tuition_exempt: boolean; note: string | null }>;
  sessions: Array<{ class_code: string; year: number; month: number; session_date: string; status: 'SCHEDULED' | 'COMPLETED' | 'CANCELLED'; teacher_code: string | null; note: string | null }>;
  attendance: Array<{ class_code: string; student_code: string; session_date: string; status: 'PRESENT' | 'ABSENT' | 'EXCUSED'; note: string | null }>;
  evaluations: Array<{ class_code: string; student_code: string; session_date: string; homework_score: number | null; understanding_score: number | null; attitude_score: number | null; learning_gap: string | null; comment: string | null }>;
  tuition_ledgers: Array<{ class_code: string; student_code: string; year: number; month: number; attended_sessions: number; absent_sessions: number; billable_sessions: number; unit_price: number; gross_amount: number; opening_debt: number; adjustment_amount: number; amount_due: number; paid_amount: number; debt_amount: number; status: 'DRAFT' | 'CONFIRMED' | 'PAID' | 'PARTIAL' | 'UNPAID' }>;
  adjustments: Array<{ class_code: string; student_code: string; year: number; month: number; type: 'DISCOUNT' | 'CARRY_IN' | 'CARRY_OUT' | 'OPENING_DEBT' | 'MANUAL'; amount: number; reason: string; source_key: string }>;
  payments: Array<{ class_code: string; student_code: string; year: number; month: number; amount: number; paid_at: string; method: 'CASH' | 'BANK_TRANSFER' | 'OTHER'; reference: string; note: string | null; source_key: string }>;
  rewards: Array<{ class_code: string | null; student_code: string; year: number; month: number; amount: number; reason: string; note: string | null; source_key: string }>;
  financial_transactions: Array<{ year: number; month: number; transaction_date: string; type: 'INCOME' | 'EXPENSE'; category: string; class_code: string | null; description: string; amount: number; source_key: string }>;
  payroll_runs: Array<{ year: number; month: number; status: 'DRAFT' | 'APPROVED' | 'PAID'; total_amount: number; source_key: string; calculated_at: string; approved_at: string | null; source_snapshot: unknown }>;
  payroll_items: Array<{ year: number; month: number; staff_code: string; class_code: string; role: 'MAIN_TEACHER' | 'ASSISTANT'; class_revenue: number; sessions_taught: number; applied_percent: number; base_amount: number; bonus: number; penalty: number; final_amount: number }>;
  fund_entries: Array<{ year: number; month: number; type: 'OPENING' | 'CONTRIBUTION' | 'WITHDRAWAL' | 'CLOSING'; amount: number; note: string }>;
  profit_distributions: Array<{ year: number; month: number; recipient_name: string; ratio: number; amount: number }>;
};

function normalize(value: unknown): string { return String(value ?? '').normalize('NFD').replace(/[Đđ]/g, 'D').replace(/[\u0300-\u036f]/g, '').toUpperCase().replace(/[^A-Z0-9]/g, ''); }
function isRef(value: unknown): boolean { return String(value ?? '').includes('#REF!'); }
function isPlaceholder(value: unknown): boolean { return ['', '-', 'KHONG', 'CHUADUNG', 'NODUNG', 'NA'].includes(normalize(value)); }
function cell(row: Record<string, unknown>, aliases: string[]): unknown { const keys = Object.keys(row); const wanted = aliases.map(normalize); const key = keys.find((item) => wanted.includes(normalize(item))); return key ? row[key] : null; }
function textCell(row: Record<string, unknown>, aliases: string[]): string { return String(cell(row, aliases) ?? '').trim(); }
function numberValue(raw: unknown): number | null {
  if (raw === null || raw === undefined || String(raw).trim() === '' || isRef(raw) || String(raw).trim() === '-') return null;
  if (typeof raw === 'number' && Number.isFinite(raw)) return raw;
  const cleaned = String(raw).replace(/[^0-9.-]/g, ''); if (!cleaned) return null;
  const parsed = Number(cleaned);
  return Number.isFinite(parsed) ? parsed : null;
}
function integerValue(raw: unknown): number | null { const parsed = numberValue(raw); return parsed !== null && Number.isSafeInteger(Math.round(parsed)) ? Math.round(parsed) : null; }
function moneyValue(raw: unknown): number | null { const parsed = numberValue(raw); return parsed === null ? null : Math.round(parsed); }
function percentValue(raw: unknown): number | null { const parsed = numberValue(raw); if (parsed === null) return null; return String(raw).includes('%') || parsed > 1 ? parsed / 100 : parsed; }
function excelSerialDate(serial: number): string | null { if (!Number.isFinite(serial) || serial < 1) return null; const date = new Date(Date.UTC(1899, 11, 30) + Math.round(serial) * 86400000); return Number.isNaN(date.getTime()) ? null : date.toISOString().slice(0, 10); }
function dateValue(raw: unknown): string | null {
  if (raw instanceof Date) return raw.toISOString().slice(0, 10);
  const text = String(raw ?? '').trim(); if (!text || isRef(raw) || text === '-') return null;
  if (/^\d{4}-\d{2}-\d{2}$/.test(text)) return text;
  const dmy = text.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/); if (dmy) return `${dmy[3]}-${dmy[2].padStart(2, '0')}-${dmy[1].padStart(2, '0')}`;
  const serial = Number(text); return Number.isFinite(serial) && serial >= 20000 ? excelSerialDate(serial) : null;
}
function periodValue(raw: unknown): { year: number; month: number } | null {
  const text = String(raw ?? '').trim(); const monthYear = text.match(/^(\d{1,2})[/-](\d{4})$/); if (monthYear) return { year: Number(monthYear[2]), month: Number(monthYear[1]) };
  const iso = dateValue(raw); return iso ? { year: Number(iso.slice(0, 4)), month: Number(iso.slice(5, 7)) } : null;
}
function periodDates(period: { year: number; month: number }): PeriodPayload { const start = `${period.year}-${String(period.month).padStart(2, '0')}-01`; const endDate = new Date(Date.UTC(period.year, period.month, 0)); return { ...period, start_date: start, end_date: endDate.toISOString().slice(0, 10) }; }
function sourceRow(row: Record<string, unknown>): number | undefined { const value = Number(row.__source_row); return Number.isInteger(value) ? value : undefined; }
function rowHasValue(row: unknown[]): boolean { return row.some((value) => value !== null && value !== undefined && String(value).trim() !== ''); }
function findHeaderRow(rawRows: unknown[][], aliases: string[]): number | null { const wanted = new Set(aliases.map(normalize)); let bestIndex: number | null = null; let bestScore = 0; rawRows.forEach((row, index) => { const values = new Set(row.filter((value) => value !== null && value !== undefined).map(normalize)); const score = [...values].filter((value) => wanted.has(value)).length; if (score > bestScore) { bestScore = score; bestIndex = index; } }); return bestScore >= 2 ? bestIndex : null; }
function rowsFor(XLSX: any, sheet: any, headerAliases: string[]): Record<string, unknown>[] { const raw = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: null, raw: false }) as unknown[][]; const header = findHeaderRow(raw, headerAliases); if (header === null) return []; return (XLSX.utils.sheet_to_json(sheet, { range: header, defval: null, raw: false }) as Record<string, unknown>[]).filter((row) => rowHasValue(Object.values(row))).map((row, index) => ({ ...row, __source_row: header + index + 2 })); }
function rawRows(XLSX: any, sheet: any): unknown[][] { return XLSX.utils.sheet_to_json(sheet, { header: 1, defval: null, raw: false }) as unknown[][]; }
function metadataCell(XLSX: any, sheet: any, aliases: string[]): unknown { if (!sheet) return null; const wanted = new Set(aliases.map(normalize)); const row = rawRows(XLSX, sheet).find((values) => values.length > 1 && wanted.has(normalize(values[0]))); return row?.[1] ?? null; }
function metadataText(XLSX: any, sheet: any, aliases: string[]): string { return String(metadataCell(XLSX, sheet, aliases) ?? '').trim(); }
function isYes(value: unknown): boolean { return ['CO', 'YES', 'TRUE', '1', 'X'].includes(normalize(value)); }
function weekdayFromHeader(value: unknown): number | null { const key = normalize(value); if (key === 'T2' || key === 'THU2') return 1; if (key === 'T3' || key === 'THU3') return 2; if (key === 'T4' || key === 'THU4') return 3; if (key === 'T5' || key === 'THU5') return 4; if (key === 'T6' || key === 'THU6') return 5; if (key === 'T7' || key === 'THU7') return 6; if (key === 'CN' || key === 'CHUNHAT') return 7; return null; }
function getOrCreatePeriod(periods: Map<string, PeriodPayload>, raw: unknown): PeriodPayload | null { const period = periodValue(raw); if (!period || period.month < 1 || period.month > 12) return null; const item = periodDates(period); periods.set(`${item.year}-${item.month}`, item); return item; }

function normalizeWorkbook(XLSX: any, workbook: any): { payload: NormalizedPayload; issues: Issue[]; summaries: unknown[]; sourceReconciliation: Record<string, unknown> } {
  const issues: Issue[] = []; const periods = new Map<string, PeriodPayload>(); const classes = new Map<string, NormalizedPayload['classes'][number]>(); const staff = new Map<string, NormalizedPayload['staff'][number]>(); const students = new Map<string, StudentPayload>(); const assignments = new Map<string, NormalizedPayload['assignments'][number]>(); const enrollments = new Map<string, NormalizedPayload['enrollments'][number]>(); const sessions = new Map<string, NormalizedPayload['sessions'][number]>(); const tuitionLedgers = new Map<string, NormalizedPayload['tuition_ledgers'][number]>(); const adjustments = new Map<string, NormalizedPayload['adjustments'][number]>(); const payments = new Map<string, NormalizedPayload['payments'][number]>(); const payrollRuns = new Map<string, NormalizedPayload['payroll_runs'][number]>();
  const attendance: NormalizedPayload['attendance'] = []; const evaluations: NormalizedPayload['evaluations'] = []; const rewards: NormalizedPayload['rewards'] = []; const financialTransactions: NormalizedPayload['financial_transactions'] = []; const payrollItems: NormalizedPayload['payroll_items'] = []; const fundEntries: NormalizedPayload['fund_entries'] = []; const profitDistributions: NormalizedPayload['profit_distributions'] = [];
  const settingValues: Record<string, unknown> = {}; const ledgerKeys = new Set<string>(); let refCount = 0; let pendingAttendanceCount = 0; let financeMetadataMissing = 0;
  const classSource = workbook.SheetNames.find((name: string) => normalize(name).includes('DANHMUCLOP')) ?? workbook.SheetNames.find((name: string) => normalize(name).includes('DANHSACHLOP')); const controlSheet = workbook.Sheets.DIEU_KHIEN; const controlRows = controlSheet ? rawRows(XLSX, controlSheet) : []; const workingPeriod = getOrCreatePeriod(periods, controlRows.find((row) => normalize(row[0]) === 'THANGLAMVIEC')?.[1]); const defaultPeriod = workingPeriod ?? periodDates({ year: 2026, month: 8 });
  settingValues.fund_percent = percentValue(controlRows.find((row) => normalize(row[0]).includes('TRICHQUY'))?.[1]) ?? 0.1; settingValues.default_payroll_percent = percentValue(controlRows.find((row) => normalize(row[0]).includes('LUONGGV'))?.[1]) ?? 0.5; settingValues.fund_opening = moneyValue(controlRows.find((row) => normalize(row[0]).includes('QUYDAUKY'))?.[1]) ?? 0; settingValues.fund_withdrawal = moneyValue(controlRows.find((row) => normalize(row[0]).includes('CHITUFQUY'))?.[1]) ?? 0; settingValues.source_file = 'TrungTam_HungCuong_T8 (1).xlsx';

  for (const sheetName of workbook.SheetNames) {
    const sheet = workbook.Sheets[sheetName]; const rows = rawRows(XLSX, sheet); const sheetRefCount = rows.reduce((count, row) => count + row.filter((value) => isRef(value)).length, 0); if (sheetRefCount > 0) { refCount += sheetRefCount; issues.push({ severity: 'WARNING', sheet_name: sheetName, code: 'REF_IGNORED', message: `Bỏ qua ${sheetRefCount} ô #REF!; không tự quy đổi thành 0`, raw_data: { count: sheetRefCount } }); }
    const key = normalize(sheetName);
    if (sheetName === classSource) {
      const headerIndex = findHeaderRow(rows, ['SLOT', 'MA LOP', 'TEN LOP']); const headerRow = rows[headerIndex ?? 2] ?? [];
      for (const row of rowsFor(XLSX, sheet, ['MA LOP', 'TEN LOP', 'SLOT', 'CODE', 'NAME'])) {
        const code = textCell(row, ['MA LOP', 'MALOP', 'CODE']); const name = textCell(row, ['TEN LOP', 'TENLOP', 'NAME']); if (isPlaceholder(code) && isPlaceholder(name)) continue; if (!code || !name) { issues.push({ severity: 'ERROR', sheet_name: sheetName, row_number: sourceRow(row), code: 'CLASS_REQUIRED_FIELDS', message: 'Lớp thiếu mã hoặc tên' }); continue; }
        const source = rows.find((candidate) => String(candidate[1] ?? '').trim() === code) ?? []; const schedules = headerRow.map((header, index) => ({ weekday: weekdayFromHeader(header), active: isYes(source[index]) })).filter((item) => item.weekday !== null && item.active).map((item) => ({ weekday: item.weekday as number, start_time: null, end_time: null })); const methodRaw = normalize(cell(row, ['CACH THU', 'COLLECTION METHOD']));
        classes.set(code, { code, name, grade: integerValue(cell(row, ['KHOI', 'GRADE'])) ?? 1, subject: textCell(row, ['MON', 'SUBJECT']) || 'Toán', standard_unit_fee: moneyValue(cell(row, ['HOC PHI', 'HOC PHI BUOI', 'DON GIA', 'PHI BUOI', 'STANDARD UNIT FEE'])) ?? 0, collection_method: (methodRaw.includes('PREPAID') || methodRaw.includes('THUTRUOC') ? 'PREPAID' : 'PER_SESSION'), status: normalize(cell(row, ['TRANG THAI', 'STATUS'])).includes('NGUNG') ? 'INACTIVE' : 'ACTIVE', note: textCell(row, ['GHI CHU', 'NOTE']) || null, schedules });
      }
    } else if ((key.includes('GIANGVIEN') || key.includes('STAFF')) && key !== 'LUONGGIANGVIEN') {
      for (const row of rowsFor(XLSX, sheet, ['MA GV', 'MA', 'MAGV', 'CODE', 'HO TEN', 'HOTEN', 'FULL NAME', 'NAME'])) { const code = textCell(row, ['MA', 'MA GV', 'MAGV', 'CODE']); const fullName = textCell(row, ['HO TEN', 'HOTEN', 'TEN', 'FULL NAME', 'NAME']); if (!code && !fullName) continue; if (!code || !fullName || isRef(code) || isRef(fullName)) { issues.push({ severity: 'ERROR', sheet_name: sheetName, row_number: sourceRow(row), code: 'STAFF_REQUIRED_FIELDS', message: 'Nhân sự thiếu mã hoặc họ tên' }); continue; } const typeRaw = normalize(cell(row, ['LOAI', 'TYPE', 'STAFF TYPE'])); const note = textCell(row, ['GHI CHU', 'NOTE']) || null; staff.set(code, { code, full_name: fullName, staff_type: typeRaw.includes('TROGIANG') || typeRaw.includes('ASSISTANT') || code.startsWith('TG') || normalize(note).includes('TROGIANG') ? 'ASSISTANT' : 'TEACHER', phone: textCell(row, ['SDT', 'PHONE']) || null, primary_subject: textCell(row, ['MON', 'MON CHINH', 'SUBJECT']) || null, status: normalize(cell(row, ['TRANG THAI', 'STATUS'])).includes('NGHI') ? 'INACTIVE' : 'ACTIVE', note }); }
    } else if (key === 'PHANCONG') {
      for (const row of rowsFor(XLSX, sheet, ['THANG', 'MA GV', 'MA LOP', 'SO BUOI'])) { const staffCode = textCell(row, ['MA GV']); const classCode = textCell(row, ['MA LOP']); if (!staffCode || !classCode) continue; const period = getOrCreatePeriod(periods, cell(row, ['THANG'])) ?? defaultPeriod; assignments.set(`${classCode}|${staffCode}|MAIN_TEACHER`, { class_code: classCode, staff_code: staffCode, role: 'MAIN_TEACHER', planned_sessions: integerValue(cell(row, ['SO BUOI'])) ?? null, start_date: period.start_date, end_date: null }); const assistantName = textCell(row, ['TRO GIANG', 'ASSISTANT']); const assistant = [...staff.values()].find((person) => normalize(person.full_name) === normalize(assistantName)); if (assistant) assignments.set(`${classCode}|${assistant.code}|ASSISTANT`, { class_code: classCode, staff_code: assistant.code, role: 'ASSISTANT', planned_sessions: null, start_date: period.start_date, end_date: null }); }
    } else if (key.startsWith('LOP')) {
      const classCode = metadataText(XLSX, sheet, ['MA LOP', 'MALOP', 'CLASS CODE']); if (!classCode) continue; const period = getOrCreatePeriod(periods, metadataCell(XLSX, sheet, ['THANG', 'MONTH'])) ?? defaultPeriod; const dateRow = rows.find((row) => normalize(row[0]) === 'NGAY') ?? []; const scheduleRow = rows.find((row) => normalize(row[0]).includes('COLICH')) ?? []; const scheduled: Array<{ index: number; date: string }> = [];
      for (let index = 2; index <= 32; index += 1) { const day = integerValue(dateRow[index]); if (day && day >= 1 && day <= 31 && isYes(scheduleRow[index])) scheduled.push({ index, date: `${period.year}-${String(period.month).padStart(2, '0')}-${String(day).padStart(2, '0')}` }); }
      const studentHeaderIndex = rows.findIndex((row) => normalize(row[0]) === 'MAHS' && normalize(row[1]).includes('HOTEN')); const studentRows = studentHeaderIndex < 0 ? [] : rows.slice(studentHeaderIndex + 1).filter((row) => String(row[0] ?? '').startsWith('HS')); const pendingBySession = new Map<number, number>();
      for (const row of studentRows) { const studentCode = String(row[0] ?? '').trim(); const fullName = String(row[1] ?? '').trim(); if (!studentCode || !fullName || isRef(studentCode) || isRef(fullName)) continue; const current = students.get(studentCode); students.set(studentCode, { ...(current ?? { code: studentCode, full_name: fullName, phone: null, parent_name: null, parent_phone: null, note: null, class_code: classCode, enrolled_from: period.start_date, unit_price_override: null }), full_name: fullName, class_code: classCode, enrolled_from: period.start_date, note: String(row[36] ?? '').trim() || current?.note || null }); enrollments.set(`${studentCode}|${classCode}`, { student_code: studentCode, class_code: classCode, enrolled_from: period.start_date, enrolled_to: null, unit_price_override: students.get(studentCode)?.unit_price_override ?? null, tuition_exempt: false, note: null });
        for (const session of scheduled) { const rawStatus = String(row[session.index] ?? '').trim().toUpperCase(); if (rawStatus === 'C') attendance.push({ class_code: classCode, student_code: studentCode, session_date: session.date, status: 'PRESENT', note: null }); else if (rawStatus === 'N') attendance.push({ class_code: classCode, student_code: studentCode, session_date: session.date, status: 'ABSENT', note: null }); else { pendingBySession.set(session.index, (pendingBySession.get(session.index) ?? 0) + 1); pendingAttendanceCount += 1; } }
        const comment = String(row[36] ?? '').trim(); if (comment) { const last = scheduled.at(-1); if (last) evaluations.push({ class_code: classCode, student_code: studentCode, session_date: last.date, homework_score: null, understanding_score: null, attitude_score: null, learning_gap: null, comment }); }
      }
      const teacherCode = [...assignments.values()].find((item) => item.class_code === classCode && item.role === 'MAIN_TEACHER')?.staff_code ?? null; for (const session of scheduled) { const pending = pendingBySession.get(session.index) ?? 0; sessions.set(`${classCode}|${session.date}`, { class_code: classCode, year: period.year, month: period.month, session_date: session.date, status: pending === 0 ? 'COMPLETED' : 'SCHEDULED', teacher_code: teacherCode, note: pending === 0 ? null : `Nguồn còn ${pending} trạng thái chưa điểm danh.` }); }
    } else if (key.startsWith('KT')) {
      const classCode = metadataText(XLSX, sheet, ['MA LOP', 'MALOP', 'CLASS CODE']); if (!classCode) continue; const period = defaultPeriod; const method = classes.get(classCode)?.collection_method ?? 'PER_SESSION'; const planned = integerValue(metadataCell(XLSX, sheet, ['SO BUOI LICH', 'SO BUOI'])) ?? 0;
      for (const row of rowsFor(XLSX, sheet, ['MA HS', 'HO TEN', 'BUOI HOC', 'DON GIA'])) { const studentCode = textCell(row, ['MA HS', 'MAHS', 'STUDENT CODE']); const fullName = textCell(row, ['HO TEN', 'HOTEN', 'TEN HS', 'FULL NAME', 'NAME']); if (!studentCode || !fullName || isRef(studentCode) || isRef(fullName)) continue; const unitPrice = moneyValue(cell(row, ['DON GIA', 'UNIT PRICE'])); const current = students.get(studentCode); if (current) students.set(studentCode, { ...current, unit_price_override: unitPrice !== null && unitPrice !== classes.get(classCode)?.standard_unit_fee ? unitPrice : current.unit_price_override }); else students.set(studentCode, { code: studentCode, full_name: fullName, phone: null, parent_name: null, parent_phone: null, note: null, class_code: classCode, enrolled_from: period.start_date, unit_price_override: unitPrice !== null && unitPrice !== classes.get(classCode)?.standard_unit_fee ? unitPrice : null }); enrollments.set(`${studentCode}|${classCode}`, { student_code: studentCode, class_code: classCode, enrolled_from: period.start_date, enrolled_to: null, unit_price_override: students.get(studentCode)?.unit_price_override ?? null, tuition_exempt: false, note: null });
        const attended = integerValue(cell(row, ['BUOI HOC', 'ATTENDED'])) ?? 0; const absent = integerValue(cell(row, ['BUOI NGHI', 'ABSENT'])) ?? 0; const gross = moneyValue(cell(row, ['HOC PHI GOC', 'GROSS'])) ?? 0; const opening = moneyValue(cell(row, ['NO DAU KY', 'OPENING DEBT'])) ?? 0; const due = moneyValue(cell(row, ['PHAI THU', 'AMOUNT DUE'])) ?? 0; const paid = moneyValue(cell(row, ['DA THU', 'PAID'])) ?? 0; const debt = moneyValue(cell(row, ['CON NO', 'DEBT'])) ?? 0; const sourceRowNumber = sourceRow(row) ?? 0; const ledgerKey = `${classCode}|${studentCode}|${period.year}-${period.month}`; ledgerKeys.add(`${classCode}|${studentCode}`); tuitionLedgers.set(ledgerKey, { class_code: classCode, student_code: studentCode, year: period.year, month: period.month, attended_sessions: attended, absent_sessions: absent, billable_sessions: method === 'PREPAID' ? planned : attended, unit_price: unitPrice ?? classes.get(classCode)?.standard_unit_fee ?? 0, gross_amount: gross, opening_debt: opening, adjustment_amount: due - gross - opening, amount_due: due, paid_amount: paid, debt_amount: debt, status: due === 0 || paid >= due ? 'PAID' : paid > 0 ? 'PARTIAL' : 'UNPAID' }); if (opening > 0) { const sourceKey = `ADJUSTMENT:${sheetName}:${sourceRowNumber}:OPENING_DEBT`; adjustments.set(sourceKey, { class_code: classCode, student_code: studentCode, year: period.year, month: period.month, type: 'OPENING_DEBT', amount: opening, reason: 'Nợ đầu kỳ theo workbook.', source_key: sourceKey }); } if (paid > 0) { const sourceKey = `PAYMENT:${sheetName}:${sourceRowNumber}`; payments.set(sourceKey, { class_code: classCode, student_code: studentCode, year: period.year, month: period.month, amount: paid, paid_at: `${period.start_date}T12:00:00+07:00`, method: 'OTHER', reference: `IMPORT:${sourceKey}`, note: 'Workbook không có ngày/phương thức thu; giữ nguyên snapshot số tiền và gắn provenance.', source_key: sourceKey }); }
      }
    } else if (key === 'CHUYENTHANG') {
      for (let rowIndex = 2; rowIndex < rows.length; rowIndex += 1) { const row = rows[rowIndex]; const addAdjustment = (offset: number, type: 'DISCOUNT' | 'CARRY_OUT', label: string) => { const classCode = String(row[offset] ?? '').trim(); const studentCode = String(row[offset + 1] ?? '').trim(); const amount = moneyValue(row[offset + 3]); if (!classCode || !studentCode || isRef(classCode) || isRef(studentCode) || amount === null || amount <= 0) return; const sourceKey = `ADJUSTMENT:${sheetName}:${rowIndex + 1}:${label}`; adjustments.set(sourceKey, { class_code: classCode, student_code: studentCode, year: defaultPeriod.year, month: defaultPeriod.month, type, amount, reason: type === 'DISCOUNT' ? 'Giảm từ tháng trước theo workbook.' : 'Giảm chuyển tháng sau theo workbook.', source_key: sourceKey }); }; addAdjustment(0, 'DISCOUNT', 'PREVIOUS'); addAdjustment(5, 'CARRY_OUT', 'NEXT'); }
    } else if (key === 'THUCHI') {
      for (const row of rowsFor(XLSX, sheet, ['NGAY', 'LOAI', 'NHOM', 'NOI DUNG', 'SO TIEN'])) { const amount = moneyValue(cell(row, ['SO TIEN', 'AMOUNT'])); if (amount === null || amount <= 0) continue; const missing = !dateValue(cell(row, ['NGAY', 'DATE'])) || !textCell(row, ['NHOM', 'CATEGORY']) || !textCell(row, ['NOI DUNG', 'DESCRIPTION']); if (missing) financeMetadataMissing += 1; const sourceRowNumber = sourceRow(row) ?? 0; const rawType = normalize(cell(row, ['LOAI', 'TYPE'])); financialTransactions.push({ year: defaultPeriod.year, month: defaultPeriod.month, transaction_date: dateValue(cell(row, ['NGAY', 'DATE'])) ?? defaultPeriod.start_date, type: rawType.includes('THU') && !rawType.includes('CHI') ? 'INCOME' : 'EXPENSE', category: textCell(row, ['NHOM', 'CATEGORY']) || 'UNMAPPED', class_code: textCell(row, ['MA LOP', 'CLASS CODE']) || null, description: textCell(row, ['NOI DUNG', 'DESCRIPTION']) || `Khoản ${rawType.includes('THU') ? 'thu' : 'chi'} import từ THU_CHI dòng ${sourceRowNumber}`, amount, source_key: `FINANCE:${sheetName}:${sourceRowNumber}` }); }
    } else if (key === 'THUONGHOCSINH') {
      for (const row of rowsFor(XLSX, sheet, ['MA LOP', 'MA HS', 'HO TEN', 'TIEN THUONG'])) { const studentCode = textCell(row, ['MA HS', 'STUDENT CODE']); const amount = moneyValue(cell(row, ['TIEN THUONG', 'AMOUNT'])); if (!studentCode || amount === null || amount <= 0) continue; const sourceRowNumber = sourceRow(row) ?? 0; rewards.push({ class_code: textCell(row, ['MA LOP', 'CLASS CODE']) || null, student_code: studentCode, year: defaultPeriod.year, month: defaultPeriod.month, amount, reason: textCell(row, ['LY DO', 'REASON']) || 'Thưởng học sinh theo workbook', note: textCell(row, ['GHI CHU', 'NOTE']) || null, source_key: `REWARD:${sheetName}:${sourceRowNumber}` }); }
    } else if (key === 'LUONGGIANGVIEN') {
      for (const row of rowsFor(XLSX, sheet, ['THANG', 'MA GV', 'MA LOP', 'THUC NHAN', 'LUONG CO SO'])) { const staffCode = textCell(row, ['MA GV']); const classCode = textCell(row, ['MA LOP']); if (!staffCode || !classCode) continue; const period = getOrCreatePeriod(periods, cell(row, ['THANG'])) ?? defaultPeriod; const sourceRowNumber = sourceRow(row) ?? 0; const item = { year: period.year, month: period.month, staff_code: staffCode, class_code: classCode, role: (staff.get(staffCode)?.staff_type === 'ASSISTANT' ? 'ASSISTANT' : 'MAIN_TEACHER') as 'MAIN_TEACHER' | 'ASSISTANT', class_revenue: moneyValue(cell(row, ['DOANH THU THUC THU LOP', 'DOANH THU THUC THU', 'CLASS REVENUE'])) ?? 0, sessions_taught: integerValue(cell(row, ['BUOI GV DAY', 'SESSIONS TAUGHT'])) ?? 0, applied_percent: percentValue(cell(row, ['% AP DUNG', 'APPLIED PERCENT'])) ?? 0, base_amount: moneyValue(cell(row, ['LUONG CO SO', 'BASE AMOUNT'])) ?? 0, bonus: moneyValue(cell(row, ['THUONG', 'BONUS'])) ?? 0, penalty: moneyValue(cell(row, ['PHAT', 'PENALTY'])) ?? 0, final_amount: moneyValue(cell(row, ['THUC NHAN', 'FINAL AMOUNT'])) ?? 0 }; payrollItems.push(item); const runKey = `${period.year}-${period.month}`; const currentRun = payrollRuns.get(runKey); payrollRuns.set(runKey, { year: period.year, month: period.month, status: 'APPROVED', total_amount: (currentRun?.total_amount ?? 0) + item.final_amount, source_key: 'WORKBOOK:LUONG_GIANG_VIEN', calculated_at: `${period.end_date}T23:59:59+07:00`, approved_at: `${period.end_date}T23:59:59+07:00`, source_snapshot: { sheet: sheetName, source_row: sourceRowNumber, default_percent: percentValue(cell(row, ['% MAC DINH', 'DEFAULT PERCENT'])), adjusted_percent: percentValue(cell(row, ['% DIEU CHINH', 'ADJUSTED PERCENT'])) } }); }
    } else if (key === 'QUYCHIA') {
      const values = new Map<string, number>(); for (const row of rows.slice(2, 20)) { const label = normalize(row[0]); const amount = moneyValue(row[1]); if (label && amount !== null) values.set(label, amount); } const opening = values.get('QUYDAUKY') ?? moneyValue(settingValues.fund_opening) ?? 0; const withdrawal = values.get('CHITUFQUY') ?? moneyValue(settingValues.fund_withdrawal) ?? 0; const contribution = values.get('TIENTRICHQUY') ?? 0; const closing = values.get('QUYCUOIKY') ?? opening + contribution - withdrawal; fundEntries.push({ year: defaultPeriod.year, month: defaultPeriod.month, type: 'OPENING', amount: opening, note: 'Số dư quỹ đầu kỳ theo workbook.' }, { year: defaultPeriod.year, month: defaultPeriod.month, type: 'WITHDRAWAL', amount: withdrawal, note: 'Chi từ quỹ theo workbook.' }, { year: defaultPeriod.year, month: defaultPeriod.month, type: 'CONTRIBUTION', amount: contribution, note: 'Trích quỹ theo workbook.' }, { year: defaultPeriod.year, month: defaultPeriod.month, type: 'CLOSING', amount: closing, note: 'Số dư quỹ cuối kỳ theo workbook.' }); for (const row of rows.slice(2, 20)) { const recipientName = String(row[3] ?? '').trim(); const ratio = percentValue(row[4]); const amount = moneyValue(row[5]); if (recipientName && ratio !== null) profitDistributions.push({ year: defaultPeriod.year, month: defaultPeriod.month, recipient_name: recipientName, ratio, amount: amount ?? 0 }); }
    }
  }
  for (const student of students.values()) if (student.class_code && !ledgerKeys.has(`${student.class_code}|${student.code}`)) issues.push({ severity: 'WARNING', sheet_name: 'KT_*', code: 'ROSTER_LEDGER_MISMATCH', message: `${student.code} có trong roster ${student.class_code} nhưng không có dòng kế toán tương ứng.`, raw_data: { student_code: student.code, class_code: student.class_code } });
  if (pendingAttendanceCount > 0) issues.push({ severity: 'WARNING', sheet_name: 'LOP_01..04', code: 'ATTENDANCE_PENDING', message: `Có ${pendingAttendanceCount} ô lịch học chưa có C/N; không tự quy đổi thành vắng.`, raw_data: { count: pendingAttendanceCount } });
  if (financeMetadataMissing > 0) issues.push({ severity: 'WARNING', sheet_name: 'THU_CHI', code: 'FINANCE_METADATA_DEFAULTED', message: `${financeMetadataMissing} khoản thu/chi thiếu ngày, nhóm hoặc nội dung; dùng ngày đầu kỳ và nhãn UNMAPPED để giữ số tiền.`, raw_data: { count: financeMetadataMissing } });
  const sourceReconciliation: Record<string, unknown> = { active_classes: classes.size, roster_students: students.size, accounting_students: ledgerKeys.size, total_due: [...tuitionLedgers.values()].reduce((sum, item) => sum + item.amount_due, 0), total_paid: [...tuitionLedgers.values()].reduce((sum, item) => sum + item.paid_amount, 0), debt: [...tuitionLedgers.values()].reduce((sum, item) => sum + item.debt_amount, 0), payroll: payrollItems.reduce((sum, item) => sum + item.final_amount, 0), other_expenses: financialTransactions.filter((item) => item.type === 'EXPENSE').reduce((sum, item) => sum + item.amount, 0), fund_contribution: fundEntries.find((item) => item.type === 'CONTRIBUTION')?.amount ?? 0, distributable_profit: profitDistributions.reduce((sum, item) => sum + item.amount, 0) };
  const settings = Object.entries(settingValues).map(([key, value_json]) => ({ key: `workbook_${normalize(key).toLowerCase()}`, value_json })); settings.push({ key: 'fund', value_json: { fund_percent: settingValues.fund_percent } });
  const payload: NormalizedPayload = { periods: [...periods.values()], settings, classes: [...classes.values()], staff: [...staff.values()], assignments: [...assignments.values()], students: [...students.values()], enrollments: [...enrollments.values()], sessions: [...sessions.values()], attendance, evaluations, tuition_ledgers: [...tuitionLedgers.values()], adjustments: [...adjustments.values()], payments: [...payments.values()], rewards, financial_transactions: financialTransactions, payroll_runs: [...payrollRuns.values()], payroll_items: payrollItems, fund_entries: fundEntries, profit_distributions: profitDistributions };
  const summaries = workbook.SheetNames.map((sheetName: string) => { const rows = rawRows(XLSX, workbook.Sheets[sheetName]); return { sheet_name: sheetName, row_count: rows.filter(rowHasValue).length, sample: rows.filter(rowHasValue).slice(0, 4) }; });
  if (workbook.SheetNames.length === 0) issues.push({ severity: 'ERROR', sheet_name: '', code: 'EMPTY_WORKBOOK', message: 'Workbook không có sheet' }); if (classes.size === 0 && staff.size === 0 && students.size === 0) issues.push({ severity: 'ERROR', sheet_name: '', code: 'NO_NORMALIZED_ROWS', message: 'Không tìm thấy dòng lớp, nhân sự hoặc học sinh theo mapping chuẩn' }); if (refCount > 0) issues.push({ severity: 'WARNING', sheet_name: 'CHUYEN_THANG', code: 'REF_TOTAL', message: `Tổng cộng ${refCount} ô #REF! được bỏ qua và lưu trong issues.` });
  return { payload, issues, summaries, sourceReconciliation };
}

export default { fetch: withSupabase({ auth: 'user' }, async (request, ctx: any) => {
  const traceId = crypto.randomUUID(); let jobId = ''; if (request.method === 'OPTIONS') return preflight(request);
  try {
    const { userId, profile } = await requireProfile(ctx, ['ADMIN']); const body = await jsonBody<Payload>(request); const admin = ctx.supabaseAdmin; if (!admin) throw new Error('INTERNAL_ERROR'); jobId = body.import_job_id ? requiredUuid(body.import_job_id) : ''; let storagePath = body.storage_path?.trim() || ''; const mode: Mode = body.mode ?? 'VALIDATE'; if (!['VALIDATE', 'IMPORT', 'RECONCILE'].includes(mode)) throw new Error('VALIDATION_ERROR');
    if (!jobId) { const fileName = requiredString(body.file_name); if (!body.file_base64) throw new Error('VALIDATION_ERROR'); const bytes = Uint8Array.from(atob(body.file_base64), (character) => character.charCodeAt(0)); jobId = crypto.randomUUID(); storagePath = `${profile.center_id}/${jobId}/${fileName.replace(/[^a-zA-Z0-9._-]/g, '_')}`; const upload = await admin.storage.from('center-imports').upload(storagePath, bytes, { contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', upsert: false }); if (upload.error) throw upload.error; const created = await admin.from('import_jobs').insert({ id: jobId, center_id: profile.center_id, file_name: fileName, storage_path: storagePath, mode, status: 'UPLOADED', created_by: userId }).select('id').single(); if (created.error) throw created.error; }
    const job = await admin.from('import_jobs').select('*').eq('id', jobId).eq('center_id', profile.center_id).maybeSingle(); if (job.error) throw job.error; if (!job.data || (!storagePath && !job.data.storage_path)) throw new Error('NOT_FOUND'); storagePath = storagePath || job.data.storage_path; const importFileName = body.file_name?.trim() || job.data.file_name || 'workbook'; const started = await admin.from('import_jobs').update({ status: mode === 'IMPORT' ? 'IMPORTING' : 'VALIDATING', mode, started_at: new Date().toISOString(), error_message: null, updated_at: new Date().toISOString() }).eq('id', jobId); if (started.error) throw started.error;
    const downloaded = await admin.storage.from('center-imports').download(storagePath); if (downloaded.error || !downloaded.data) throw downloaded.error ?? new Error('IMPORT_VALIDATION_FAILED'); const XLSX = await import('npm:xlsx@0.18.5'); const workbook = XLSX.read(new Uint8Array(await downloaded.data.arrayBuffer()), { type: 'array', cellDates: false, cellFormula: true }); const normalized = normalizeWorkbook(XLSX, workbook); const issueRows = normalized.issues.map((issue) => ({ import_job_id: jobId, ...issue })); const cleared = await admin.from('import_job_issues').delete().eq('import_job_id', jobId); if (cleared.error) throw cleared.error; if (issueRows.length) { const inserted = await admin.from('import_job_issues').insert(issueRows); if (inserted.error) throw inserted.error; }
    const hasErrors = normalized.issues.some((issue) => issue.severity === 'ERROR'); const baseSummary = { sheets: normalized.summaries, normalized_counts: { periods: normalized.payload.periods.length, classes: normalized.payload.classes.length, staff: normalized.payload.staff.length, students: normalized.payload.students.length, enrollments: normalized.payload.enrollments.length, sessions: normalized.payload.sessions.length, attendance: normalized.payload.attendance.length, evaluations: normalized.payload.evaluations.length, tuition_ledgers: normalized.payload.tuition_ledgers.length, payments: normalized.payload.payments.length, adjustments: normalized.payload.adjustments.length, financial_transactions: normalized.payload.financial_transactions.length, payroll_items: normalized.payload.payroll_items.length }, source_reconciliation: normalized.sourceReconciliation, issue_count: normalized.issues.length, error_count: normalized.issues.filter((issue) => issue.severity === 'ERROR').length, trace_id: traceId }; if (mode === 'IMPORT' && hasErrors) throw new Error('IMPORT_VALIDATION_FAILED');
    if (mode === 'IMPORT') { const imported = await ctx.supabase.rpc('rpc_import_normalized_workbook', { p_import_job_id: jobId, p_payload: normalized.payload, p_trace_id: traceId }); if (imported.error) throw imported.error; const summary = { ...baseSummary, imported: imported.data }; const updated = await admin.from('import_jobs').update({ status: 'COMPLETED', summary, completed_at: new Date().toISOString(), updated_at: new Date().toISOString(), error_message: null }).eq('id', jobId); if (updated.error) throw updated.error; return finish(request, ok({ import_job_id: jobId, status: 'COMPLETED', summary, issues: normalized.issues }, traceId)); }
    const status = hasErrors ? 'FAILED' : 'READY'; const summary = mode === 'RECONCILE' ? { ...baseSummary, reconciliation: { status: 'READY_SOURCE_TOTALS', source: normalized.sourceReconciliation } } : baseSummary; const updated = await admin.from('import_jobs').update({ status, summary, completed_at: new Date().toISOString(), updated_at: new Date().toISOString(), error_message: hasErrors ? 'IMPORT_VALIDATION_FAILED' : null }).eq('id', jobId); if (updated.error) throw updated.error;
    if (hasErrors) {
      const notified = await ctx.supabase.rpc('rpc_publish_admin_notification', { p_type: 'IMPORT_ERROR', p_title: 'Import có lỗi cần xử lý', p_message: `File ${importFileName} có ${baseSummary.error_count} lỗi validation; dữ liệu chưa được import.`, p_severity: 'BLOCKED', p_action_route: '/settings?tab=migration', p_metadata: { import_job_id: jobId, error_count: baseSummary.error_count }, p_dedupe_key: `IMPORT_ERROR:${jobId}`, p_trace_id: traceId });
      if (notified.error) throw notified.error;
    }
    return finish(request, ok({ import_job_id: jobId, status, summary, issues: normalized.issues }, traceId));
  } catch (error) { const errorMessage = error instanceof Error ? error.message : (typeof error === 'object' && error !== null && 'message' in error ? String((error as { message?: unknown }).message ?? 'IMPORT_FAILED') : String(error ?? 'IMPORT_FAILED')); if (jobId && ctx.supabaseAdmin) await ctx.supabaseAdmin.from('import_jobs').update({ status: 'FAILED', error_message: errorMessage.slice(0, 1000), updated_at: new Date().toISOString() }).eq('id', jobId); if (jobId) { try { await ctx.supabase.rpc('rpc_publish_admin_notification', { p_type: 'IMPORT_ERROR', p_title: 'Import thất bại', p_message: `Import ${jobId} thất bại: ${errorMessage.slice(0, 240)}`, p_severity: 'BLOCKED', p_action_route: '/settings?tab=migration', p_metadata: { import_job_id: jobId, error: errorMessage }, p_dedupe_key: `IMPORT_ERROR:${jobId}`, p_trace_id: traceId }); } catch { /* notification must not hide the original import error */ } } return errorResponse(error, request, traceId); }
}) };
