import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { ToastService } from '../../core/services/toast.service';
import { AuthService } from '../../core/auth/auth.service';
@Component({selector:'app-staff',standalone:true,imports:[FormsModule,RouterLink],template:`
<section class="page-header"><div><p class="eyebrow">NHÂN SỰ</p><h1>Giảng viên & trợ giảng</h1></div>@if(auth.role()==='ADMIN'){<button class="primary" (click)="showForm=!showForm">{{showForm?'Đóng':'+ Thêm nhân sự'}}</button>}</section>@if(showForm&&auth.role()==='ADMIN'){<form class="card form-card" (ngSubmit)="save()"><div class="form-grid"><label>Mã *<input name="code" [(ngModel)]="form.code" required /></label><label>Họ tên *<input name="full_name" [(ngModel)]="form.full_name" required /></label><label>Loại<select name="staff_type" [(ngModel)]="form.staff_type"><option value="TEACHER">Giáo viên</option><option value="ASSISTANT">Trợ giảng</option></select></label><label>SĐT<input name="phone" [(ngModel)]="form.phone" /></label><label>Môn<input name="subject" [(ngModel)]="form.primary_subject" /></label></div>@if(error()){<div class="alert">{{error()}}</div>}<button class="primary">Lưu</button></form>}@if(error()&&!showForm){<div class="alert">{{error()}}</div>}<div class="card table-wrap"><table><thead><tr><th>Mã</th><th>Họ tên</th><th>Loại</th><th>Môn</th><th>SĐT</th><th>Trạng thái</th></tr></thead><tbody>@for(item of items();track item.id){<tr><td><a class="button-link" [routerLink]="['/staff',item.id]">{{item.code}}</a></td><td>{{item.full_name}}</td><td>{{item.staff_type==='TEACHER'?'Giáo viên':'Trợ giảng'}}</td><td>{{item.primary_subject||'—'}}</td><td>{{item.phone||'—'}}</td><td>{{item.status}}</td></tr>}@empty{<tr><td colspan="6" class="empty">Chưa có nhân sự.</td></tr>}</tbody></table></div>
`})
export class StaffComponent implements OnInit{items=signal<any[]>([]);error=signal('');showForm=false;form={code:'',full_name:'',staff_type:'TEACHER',phone:'',primary_subject:'Toán'};constructor(private readonly supabase:SupabaseService,private readonly toast:ToastService,readonly auth:AuthService){}ngOnInit(){void this.load();}async load(){const r=await this.supabase.client.from('staff').select('*').order('full_name');if(r.error)this.error.set(r.error.message);else this.items.set(r.data||[]);}async save(){if(!this.form.code.trim()||!this.form.full_name.trim()){this.error.set('Mã và họ tên là bắt buộc.');return;}const r=await this.supabase.client.rpc('rpc_create_staff',{p_code:this.form.code.trim(),p_full_name:this.form.full_name.trim(),p_staff_type:this.form.staff_type,p_phone:this.form.phone.trim()||null,p_primary_subject:this.form.primary_subject.trim()||null});if(r.error)this.error.set(r.error.message);else{this.toast.success('Đã thêm nhân sự.');this.showForm=false;this.form={code:'',full_name:'',staff_type:'TEACHER',phone:'',primary_subject:'Toán'};await this.load();}}}
