import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { PeriodContextService } from '../../core/services/period-context.service';
@Component({selector:'app-attendance',standalone:true,imports:[FormsModule,RouterLink],template:`
<section class="page-header"><div><p class="eyebrow">ĐÀO TẠO</p><h1>Điểm danh</h1><p class="muted">Chọn buổi học để cập nhật C / N / P.</p></div><button class="secondary" (click)="load()">Làm mới</button></section>@if(error()){<div class="alert">{{error()}}</div>}<div class="toolbar"><label>Lớp<select [(ngModel)]="classId"><option value="">Tất cả lớp</option>@for(c of classes();track c.id){<option [value]="c.id">{{c.code}} · {{c.name}}</option>}</select></label><label>Trạng thái<select [(ngModel)]="status"><option value="">Tất cả</option><option value="SCHEDULED">Chưa điểm danh</option><option value="COMPLETED">Đã hoàn tất</option></select></label></div><div class="card table-wrap"><table><thead><tr><th>Ngày</th><th>Lớp</th><th>Giờ</th><th>Trạng thái</th><th></th></tr></thead><tbody>@for(s of filtered();track s.id){<tr><td>{{s.session_date}}</td><td>{{s.class?.code}} · {{s.class?.name}}</td><td>{{s.start_time||'—'}}</td><td><span class="badge" [class.active]="s.status==='COMPLETED'">{{s.status}}</span></td><td><a class="button-link" [routerLink]="['/attendance',s.id]">Điểm danh</a> · <a class="button-link" [routerLink]="['/evaluations',s.id]">Đánh giá</a></td></tr>}@empty{<tr><td colspan="5" class="empty">Chưa có buổi học trong kỳ hiện tại.</td></tr>}</tbody></table></div>
`})
export class AttendanceComponent implements OnInit{classes=signal<any[]>([]);sessions=signal<any[]>([]);error=signal('');classId='';status='';constructor(private readonly supabase:SupabaseService,readonly period:PeriodContextService){}ngOnInit(){void this.load();}async load(){const p=this.period.current();if(!p)return;const c=await this.supabase.client.from('classes').select('id,code,name').order('grade');if(!c.error)this.classes.set(c.data||[]);const s=await this.supabase.client.from('class_sessions').select('id,class_id,session_date,start_time,status,class:classes(code,name)').eq('period_id',p.id).order('session_date',{ascending:false});if(s.error)this.error.set(s.error.message);else this.sessions.set(s.data||[]);}filtered(){return this.sessions().filter(s=>(!this.classId||s.class_id===this.classId)&&(!this.status||s.status===this.status));}}
