import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { SupabaseService } from '../../core/supabase/supabase.service';
import { EdgeFunctionService } from '../../core/api/edge-function.service';
import { ToastService } from '../../core/services/toast.service';
@Component({selector:'app-attendance-session',standalone:true,imports:[FormsModule,RouterLink],template:`
<section class="page-header"><div><p class="eyebrow">ĐIỂM DANH</p><h1>{{session()?.class?.name||'Buổi học'}}</h1><p class="muted">{{session()?.session_date}} · {{session()?.start_time||'Không đặt giờ'}}</p></div><a class="secondary" routerLink="/attendance">Danh sách buổi</a></section>@if(error()){<div class="alert">{{error()}}</div>}<section class="card section-card"><div class="page-header"><h2>Roster ({{rows().length}})</h2><div><button class="secondary" (click)="markAll('PRESENT')">Tất cả có mặt</button><button class="primary" [disabled]="saving" (click)="save()">{{saving?'Đang lưu…':'Lưu điểm danh'}}</button></div></div><div class="table-wrap"><table><thead><tr><th>Mã HS</th><th>Họ tên</th><th>Trạng thái</th><th>Ghi chú</th></tr></thead><tbody>@for(row of rows();track row.enrollment_id){<tr><td>{{row.student?.code}}</td><td>{{row.student?.full_name}}</td><td><select [(ngModel)]="row.status"><option value="PRESENT">C · Có mặt</option><option value="ABSENT">N · Vắng</option><option value="EXCUSED">P · Có phép</option></select></td><td><input [(ngModel)]="row.note" placeholder="Ghi chú" /></td></tr>}@empty{<tr><td colspan="4" class="empty">Không có roster active.</td></tr>}</tbody></table></div></section>
`})
export class AttendanceSessionComponent implements OnInit{id='';session=signal<any>(null);rows=signal<any[]>([]);error=signal('');saving=false;constructor(private readonly route:ActivatedRoute,private readonly supabase:SupabaseService,private readonly edge:EdgeFunctionService,private readonly toast:ToastService){}ngOnInit(){this.id=this.route.snapshot.paramMap.get('sessionId')||'';void this.load();}async load(){const s=await this.supabase.client.from('class_sessions').select('id,class_id,period_id,session_date,start_time,status,class:classes(name,code)').eq('id',this.id).maybeSingle();if(s.error)this.error.set(s.error.message);else this.session.set(s.data);if(!s.data)return;const e=await this.supabase.client.from('enrollments').select('id,student:students(code,full_name)').eq('class_id',s.data.class_id).eq('status','ACTIVE');const a=await this.supabase.client.from('attendance').select('enrollment_id,status,note').eq('session_id',this.id);const map=new Map((a.data||[]).map((x:any)=>[x.enrollment_id,x]));if(!e.error)this.rows.set((e.data||[]).map((x:any)=>({enrollment_id:x.id,student:x.student,status:map.get(x.id)?.status||'PRESENT',note:map.get(x.id)?.note||''})));}markAll(status:string){this.rows.update(rows=>rows.map(row=>({...row,status})));}async save(){this.saving=true;try{await this.edge.invoke('attendance-bulk-upsert',{session_id:this.id,items:this.rows().map(row=>({enrollment_id:row.enrollment_id,status:row.status,note:row.note||null}))});this.toast.success('Đã lưu điểm danh.');}catch(e){this.error.set(e instanceof Error?e.message:'Không thể lưu điểm danh.');}finally{this.saving=false;}}}
